compras/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('compras/requisiciones_autorizadas', views.requisiciones_autorizadas, name='requisicion-autorizada'),
    path('compras/oc/<int:pk>/', views.oc_modal, name='oc'),
    path('update_oc/', views.update_oc, name='update-oc'),
    path('compras/matriz_compras/', views.matriz_oc, name='matriz-compras'),
    path('compras/upload_facturas/<int:pk>/', views.upload_facturas, name='upload-facturas'),
    path('compras/upload_xml/<int:pk>/', views.upload_xml, name='upload-xml'),
    path('compras/autorizacion_oc1/',views.autorizacion_oc1, name='autorizacion-oc1'),
    path('compras/autorizacion_oc2/',views.autorizacion_oc2, name='autorizacion-oc2'),
    path('compras/cancelar_oc1/<int:pk>/',views.cancelar_oc1, name='cancelar-oc1'),
    path('compras/regresar_oc/<int:pk>/',views.back_oc, name='back-oc'),
    path('compras/cancelar_oc2/<int:pk>/',views.cancelar_oc2, name='cancelar-oc2'),
    path('compras/autorizar_oc1/<int:pk>/', views.autorizar_oc1, name='autorizar-oc1'),
    path('compras/autorizar_oc2/<int:pk>/', views.autorizar_oc2, name='autorizar-oc2'),
    path('salida_material/oc_pdf/<int:pk>/', views.descargar_pdf, name='oc-pdf'),
    path('compras/productos_oc/<int:pk>/', views.productos_oc, name='productos-oc'),
    path('compras/eliminar_articulos/<int:pk>', views.eliminar_articulos, name='eliminar-articulos'),
    path('compras/articulos_restantes/<int:pk>', views.articulos_restantes, name='articulos-restantes'),
    path('compras/productos_pendientes/', views.productos_pendientes, name='productos-pendientes'),
    path('compras/compras_devueltas', views.compras_devueltas,name='compras-devueltas'),
    path('compras/compra_edicion/<int:pk>', views.compra_edicion, name='compra-edicion'),
    path('compras/matriz_oc_productos/', views.matriz_oc_productos, name='matriz-oc-productos'),
    path('compras/comparativos', views.comparativos, name='comparativos'),
    path('compras/crear_comparativo', views.crear_comparativo, name='crear_comparativo'),
    path('compras/articulos_comparativo/<int:pk>', views.articulos_comparativo, name='articulos-comparativo'),
    path('compras/articulo_comparativo_delete/<int:pk>', views.articulo_comparativo_delete, name='articulo-comparativo-delete'),
    path('compras/historico_articulos_compras', views.historico_articulos_compras, name='historico-articulos-compras'),
    path('compras/mostrar_comparativo/<int:pk>', views.mostrar_comparativo, name='mostrar-comparativo'),
    path('editar_comparativo/<int:pk>/', views.editar_comparativo, name='editar-comparativo'),
    path('compras/preevaluacion/<int:pk>', views.preevaluacion, name='preevaluacion'),
    path('compras/preevaluaciones/<int:pk>', views.preevaluaciones, name='preevaluaciones'),
    path('compras/autorizacion_preevaluaciones', views.autorizacion_preevaluacion, name='autorizacion-preevaluacion'),
    path('compras/autorizar_preevaluacion/<int:pk>', views.autorizar_preevaluacion, name='autorizar-preevaluacion'),
    ]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_URL)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_URL)

inventoryproject/urls.py
from django.contrib import admin
from django.urls import path, include
from user import views as user_view
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from user.forms import EmailLoginForm


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('dashboard.urls')),
    path('solicitudes/', include('solicitudes.urls')),
    path('requisiciones/', include('requisiciones.urls')),
    path('compras/', include('compras.urls')),
    path('entradas/', include('entradas.urls')),
    path('tesoreria/', include('tesoreria.urls')),
    path('cobranza/', include('cobranza.urls')),
    path('viaticos/', include('viaticos.urls')),
    path('gastos/', include('gastos.urls')),
    path('activos/', include('activos.urls')),
    path('user/', include('user.urls')),
    path('register/', user_view.register, name='user-register'),
    path('profile/', user_view.profile, name='user-profile'),
    #path('', auth_views.LoginView.as_view(template_name='user/login.html'), name='user-login'),
    path('', auth_views.LoginView.as_view(template_name='user/login.html', authentication_form=EmailLoginForm), name='user-login'),
    path('password-reset/', auth_views.PasswordResetView.as_view(
        template_name='user/password_reset.html',
        email_template_name='user/password_reset_email.html',
        subject_template_name = 'user/password_reset_subject.txt'
    ), name='password-reset'),
    path('logout/', auth_views.LogoutView.as_view(template_name='user/logout.html'), name='user-logout'),
] # static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('user/edit_profile/', views.edit_profile, name='edit-profile'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(
        template_name='user/password_reset_done.html'
    ), name='password_reset_done'),
    
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='user/password_reset_confirm.html'
    ), name='password_reset_confirm'),
    
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(
        template_name='user/password_reset_complete.html'
    ), name='password_reset_complete'),
    # ...
]

compras/models.py
from django.db import models
from dashboard.models import Order, Inventario, ArticulosparaSurtir, Familia, Criticidad
from requisiciones.models import Requis, ArticulosRequisitados
from user.models import Profile, Distrito, Banco
from simple_history.models import HistoricalRecords
from django.core.validators import FileExtensionValidator
import decimal
from phone_field import PhoneField
# Create your models here.



class Estatus_proveedor(models.Model):
    nombre = models.CharField(max_length=15, null=True, unique=True)

    def __str__(self):
        return f'{self.nombre}'


class Proveedor(models.Model):
    razon_social = models.CharField(max_length=100, null=True, unique=True)
    nombre_comercial = models.CharField(max_length=100, null=True, blank=True)
    rfc = models.CharField(max_length=13, null=True, unique=True)
    creado_por = models.ForeignKey(Profile, on_delete = models.CASCADE, null=True)
    completo = models.BooleanField(default=False)
    familia = models.ForeignKey(Familia, on_delete = models.CASCADE, null=True)
    history = HistoricalRecords(history_change_reason_field=models.TextField(null=True))


    def __str__(self):
        return f'{self.razon_social}'

class Proveedor_Batch(models.Model):
    file_name = models.FileField(upload_to='product_bash', validators = [FileExtensionValidator(allowed_extensions=('csv',))])
    uploaded = models.DateField(auto_now_add=True)
    activated = models.BooleanField(default=False)


    def __str__(self):
        return f'File id:{self.id}'

class Estado(models.Model):
    nombre = models.CharField(max_length=30, null=True)

    def __str__(self):
        return f'{self.nombre}'


class Proveedor_direcciones(models.Model):
    nombre = models.ForeignKey(Proveedor, on_delete=models.CASCADE, null=True)
    creado_por = models.ForeignKey(Profile, on_delete = models.CASCADE, null=True)
    distrito = models.ForeignKey(Distrito, on_delete=models.CASCADE, null=True)
    domicilio = models.CharField(max_length=200, null=True)
    telefono = models.CharField(max_length=14, null=True)
    estado = models.ForeignKey(Estado, on_delete=models.CASCADE, null=True, blank=True)
    contacto = models.CharField(max_length=50, null=True)
    email = models.EmailField(max_length=254, null=True)
    email_opt = models.EmailField(max_length=100, null=True, blank=True)
    banco = models.ForeignKey(Banco, on_delete=models.CASCADE, null=True)
    clabe = models.CharField(max_length=20, null=True)
    cuenta = models.CharField(max_length=20, null=True)
    swift = models.CharField(max_length=20, null=True, blank=True)
    financiamiento = models.BooleanField(null=True, default=False)
    dias_credito = models.PositiveIntegerField(null=True)
    estatus = models.ForeignKey(Estatus_proveedor, on_delete=models.CASCADE, null=True)
    history = HistoricalRecords(history_change_reason_field=models.TextField(null=True))
    completo = models.BooleanField(default=False)
    modified = models.DateField(auto_now=True)
    actualizado_por = models.ForeignKey(Profile, on_delete = models.CASCADE, null=True, related_name='Des_proveedores' )
    modificado_fecha = models.DateField(null=True)
    enviado_fecha = models.DateField(null=True)

    def __str__(self):
        return f'{self.nombre}'
    
class Tipo_Evaluacion(models.Model):
    nombre = models.CharField(max_length=20, null=True, blank=True)

    def __str__(self):
        return f'{self.nombre}'
    
class Comparativo(models.Model):
    nombre = models.CharField(max_length=100, null=True)
    proveedor = models.ForeignKey(Proveedor_direcciones, on_delete = models.CASCADE, null=True)
    proveedor2 = models.ForeignKey(Proveedor_direcciones, on_delete = models.CASCADE, null=True, related_name='proveedor2') 
    proveedor3 = models.ForeignKey(Proveedor_direcciones, on_delete = models.CASCADE, null=True, related_name='proveedor3')
    cotizacion = models.FileField(blank=True, null=True, upload_to='facturas',validators=[FileExtensionValidator(['pdf'])]) 
    cotizacion2 = models.FileField(blank=True, null=True, upload_to='facturas',validators=[FileExtensionValidator(['pdf'])])
    cotizacion3 = models.FileField(blank=True, null=True, upload_to='facturas',validators=[FileExtensionValidator(['pdf'])])
    creada_por = models.ForeignKey(Profile, on_delete = models.CASCADE, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    completo = models.BooleanField(default=False)
    comentarios = models.TextField(max_length=200, null=True)

    def __str__(self):
        return f'{self.nombre}'
    
class Preevaluacion(models.Model):
    nombre = models.ForeignKey(Proveedor, on_delete=models.CASCADE, null=True, related_name = "preevaluacion")
    creado_por = models.ForeignKey(Profile, on_delete = models.CASCADE, null=True)
    creado_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(null=True)
    tipo_evaluacion = models.ForeignKey(Tipo_Evaluacion, on_delete= models.CASCADE, null=True)
    criticidad = models.ForeignKey(Criticidad, on_delete= models.CASCADE, null=True)
    requisitos_sgc_ver = models.CharField(max_length=255, null=True, blank=True)  #Campo para la evaluacion inicial
    sgc_b = models.BooleanField(default=False)  #Campo para la evaluacion inicial 
    especs_ver = models.CharField(max_length=255, null=True, blank=True) #Campo para la evaluacion inicial simplificada
    especs_b = models.BooleanField(default=False) #Campo para la evaluacion inicial simplificada
    precios_ver = models.CharField(max_length=255, null=True, blank=True) #Campo para la evaluacion inicial simplificada
    precios_b = models.BooleanField(default = False) #Campo para la evaluacion inicial simplificada
    control_cadena_suministro = models.CharField(max_length=255, null=True, blank=True)  #Campo para la evaluacion inicial simplificada
    control_cadena_b= models.BooleanField(default = False) #Campo para la evaluacion inicial simplificada
    resultado = models.BooleanField(default= None, null=True)
    capacidad_proveedor = models.CharField(max_length=255, null=True, blank=True)  #Campo para la evaluacion inicial simplificada
    capacidad_proveedor_b= models.BooleanField(default = False) #Campo para la evaluacion inicial simplificada
    areas_exito = models.CharField(max_length=255, null=True, blank=True)
    areas_oportunidad = models.CharField(max_length=255, null=True, blank=True)
    history = HistoricalRecords(history_change_reason_field=models.TextField(null=True))
    completo = models.BooleanField(default=False)
    comparativo_model = models.ForeignKey(Comparativo, on_delete = models.CASCADE, null=True, blank=True)

    def __str__(self):
        return f'{self.id} - {self.nombre}'


class Proveedor_Direcciones_Batch(models.Model):
    file_name = models.FileField(upload_to='product_bash', validators = [FileExtensionValidator(allowed_extensions=('csv',))])
    uploaded = models.DateField(auto_now_add=True)
    activated = models.BooleanField(default=False)

class Uso_cfdi(models.Model):
    codigo = models.CharField(max_length=3, null=True)
    descripcion = models.CharField(max_length=30, null=True)

    def __str__(self):
        return f'{self.codigo} - {self.descripcion}'

class Cond_credito(models.Model):
    nombre = models.CharField(max_length=20)

    def __str__(self):
        return f'{self.nombre}'

class Moneda(models.Model):
    nombre = models.CharField(max_length=20)

    def __str__(self):
        return f'{self.nombre}'
    


class Item_Comparativo(models.Model):
    producto = models.ForeignKey(Inventario, on_delete = models.CASCADE, null=True)
    comparativo = models.ForeignKey(Comparativo, on_delete = models.CASCADE, null=True)
    modelo = models.CharField(max_length=100, null=True, blank=True)
    marca = models.CharField(max_length=100, null=True, blank=True)
    cantidad = models.DecimalField(max_digits=14, decimal_places=2, default=0)
    precio = models.DecimalField(max_digits=14, decimal_places=4, null=True, blank=True)
    dias_de_entrega = models.PositiveIntegerField(null=True, blank=True)
    modelo2 = models.CharField(max_length=100, null=True, blank=True)
    marca2 = models.CharField(max_length=100, null=True, blank=True)
    precio2 = models.DecimalField(max_digits=14, decimal_places=4, null=True, blank=True)
    dias_de_entrega2 = models.PositiveIntegerField(null=True, blank=True)
    modelo3 = models.CharField(max_length=100, null=True, blank=True)
    marca3 = models.CharField(max_length=100, null=True, blank=True)
    precio3 = models.DecimalField(max_digits=14, decimal_places=4, null=True, blank=True)
    dias_de_entrega3 = models.PositiveIntegerField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    completo = models.BooleanField(default=False)

class Compra(models.Model):
    req = models.ForeignKey(Requis, on_delete = models.CASCADE, null=True, related_name = 'compras')
    folio = models.CharField(max_length=7, null=True)
    complete = models.BooleanField(default=False)
    creada_por = models.ForeignKey(Profile, on_delete = models.CASCADE, null=True, related_name='Generacion')
    created_at = models.DateField(auto_now_add=True)
    created_time = models.TimeField(auto_now_add=True)
    oc_autorizada_por = models.ForeignKey(Profile, on_delete = models.CASCADE, null=True, blank=True, related_name='Aprobacion')
    autorizado_date1 = models.DateField(null=True, blank=True)
    autorizado_hora1 = models.TimeField(null=True, blank=True)
    autorizado1 = models.BooleanField(null=True, default=None)
    oc_autorizada_por2 = models.ForeignKey(Profile, on_delete = models.CASCADE, null=True, blank=True,related_name='Aprobacion2')
    autorizado_date2 = models.DateField(null=True, blank=True)
    autorizado_hora2 = models.TimeField(null=True, blank=True)
    autorizado2 = models.BooleanField(null=True, default=None)

compras/forms.py
from django import forms
from .models import Compra, ArticuloComprado, Comparativo, Item_Comparativo, Preevaluacion
from requisiciones.models import ArticulosRequisitados

class CompraForm(forms.ModelForm):
    class Meta:
        model = Compra
        fields = ['id','proveedor','cond_de_pago','uso_del_cfdi','dias_de_credito','deposito_comprador','anticipo',
                  'monto_anticipo','dias_de_entrega','impuesto','impuestos_adicionales','flete','costo_fletes',
                  'tesoreria_matriz','opciones_condiciones','moneda','tipo_de_cambio','logistica', 'referencia','comparativo_model']

class ArticuloCompradoForm(forms.ModelForm):
    class Meta:
        model = ArticuloComprado
        fields = ['producto','cantidad','precio_unitario']

class ArticulosRequisitadosForm(forms.ModelForm):

    class Meta:
        model = ArticulosRequisitados
        fields = ['producto','cantidad']

class ComparativoForm(forms.ModelForm):
    class Meta:
        model = Comparativo
        fields = ['nombre','comentarios','proveedor', 'proveedor2','proveedor3','cotizacion','cotizacion2', 'cotizacion3']

class Item_ComparativoForm(forms.ModelForm):
    class Meta:
        model = Item_Comparativo
        fields = ['producto','modelo','marca','cantidad', 'precio','dias_de_entrega', 'modelo2', 'marca2','dias_de_entrega2', 
                  'precio2','modelo3','marca3','precio3','dias_de_entrega3',]

class Compra_ComentarioForm(forms.ModelForm):
    class Meta:
        model = Compra
        fields = ['comentarios']

class PreevaluacionForm(forms.ModelForm):
    class Meta:
        model = Preevaluacion
        fields = ['tipo_evaluacion','comparativo_model','especs_ver','especs_b','precios_ver','precios_b','control_cadena_suministro','control_cadena_b','capacidad_proveedor','capacidad_proveedor_b','requisitos_sgc_ver','sgc_b']

templates/compras/articulos_restantes.html
{% extends 'partials/base.html' %}
{% load static %}

<html>
<head>
{% block title %}Solicitudes{% endblock %}
</head>

<body>
{% block content %}
<h6>&nbsp;</h6>
<h6>&nbsp;</h6>
<h6>&nbsp;</h6>
<div class="row">
    <div class="col-lg-10 offset-md-1">
        <div class="card">
            <div class="card-header">
                <h5 class="modal-title">Requisicion: {{requis.folio}}</h5>
            </div>

            <div class="card-body">
                <div class ="table-responsive-sm">
                    <table class="table table-ligth table-striped mx-1">
                        <thead>
                            <tr>
                                <th scope="col">Cantidad Restante</th>
                                <th scope="col">Código</th>
                                <th scope="col">Artículo</th>
                                <th>Producto/Serivicio</th>
                                <th scope="col">Unidad</th>
                                <th>Comentario Usuario</th>
                                <th>Especificaciones Técnicas</th>
                                <th>Criticidad</th>
                                <th>Requisitos</th>
                                <th style="text-align: center;">Documental</th>
                                <th style="text-align: center;">Grado</th>
                                <th style="text-align: center;">Inspección</th>
                                <th style="text-align: center;">Grado</th>
                                <th style="text-align: center;">Cumplimiento</th>
                                <th style="text-align: center;">Grado</th>
                            </tr>
                        </thead>
                        <tbody id="mytbl">
                            {% for producto in productos %}
                            <tr>
                                <td scope="col"><p class='quantity' id='prod_quantity'>{{producto.cantidad}}</p></td>
                                <td scope="col">{{producto.producto.articulos.producto.producto.codigo}}</td>
                                <td scope="col">{{producto.producto.articulos.producto.producto.nombre}}</td>
                                <td scope="col">{{producto.producto.articulos.producto.producto.unidad}}</td>
                                <td scope="col">{% if producto.producto.articulos.producto.producto.servicio %} Servicio {% else %} Producto {% endif %}</td>
                                <td>{{producto.producto.articulos.producto.producto.especs}}</td>
                                <td>{% if producto.producto.articulos.comentario %}{{producto.producto.articulos.comentario}} {% endif %}</td>
                                {% if producto.producto.articulos.producto.producto.critico.nombre == "Crítico" %}
                                <td>
                                    <button type="button" class="btn btn-danger"><i class="fa-solid fa-q"></i></button>
                                </td>
                                <td>
                                    {{producto.producto.articulos.producto.producto.producto_calidad.requisitos}}
                                </td>
                                <td style="text-align: center;">
                                    {%if producto.producto.articulos.producto.producto.producto_calidad.documental %}
                                        <div class="alert alert-success" role="alert">
                                        <i class="fa-regular fa-circle-check"></i>
                                        </div>
                                    {% endif %} 
                                </td>
                                <td style="text-align: center;">{{producto.producto.articulos.producto.producto.producto_calidad.g_documental}}</td>
                                <td style="text-align: center;">
                                    {% if producto.producto.articulos.producto.producto.producto_calidad.inspeccion %}
                                    <div class="alert alert-success" role="alert">
                                        <i class="fa-regular fa-circle-check"></i>
                                    </div>
                                    {% endif %} 
                                </td>
                                <td style="text-align: center;">{{producto.producto.articulos.producto.producto.producto_calidad.g_inspeccion}}</td>
                                <td style="text-align: center;">
                                    {% if producto.producto.articulos.producto.producto.producto_calidad.cumplimiento %}
                                    <div class="alert alert-success" role="alert">
                                        <i class="fa-regular fa-circle-check"></i>
                                    </div>
                                    {% endif %} 
                                </td>
                                <td>{{producto.producto.articulos.producto.producto.producto_calidad.g_cumplimiento}}</td>
                                {% endif %}
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            
                <h6>Comentario Superintendente:   {%if requis.comentario_super%} {{requis.comentario_super}} {%else%} No hay comentario {%endif%}</h6>
                <h6>Comentario Almacén: {%if requis.comentario_compras %} {{requis.comentario_compras}} {% else %}No hay comentario{% endif %}</h6>
                <h6>Comentario Usuario: {%if requis.orden.comentario %} {{requis.orden.comentario}} {% else %} No hay comentario {% endif %}</h6>  
            </div>

            <div class="card-footer">
                <div class="container-fluid text-end">
                    <a id="myBtn" type="button" class="btn btn-lg btn-outline-info col-lg-3 col-md-12 col-sm-12 col-xs-12" href="{% url 'requisicion-autorizada' %}">Cerrar</a>
                </div>
            </div>
        </div>
    </div>
</div>



{% endblock %}
</body>
</html>

templates/compras/back_oc.html
{% extends 'partials/base_w_nav.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% load widget_tweaks %}
<html>
<head>
{% block title %}Devolver OC{% endblock %}
</head>
<body>
{% block content %}
    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title" id="compra" value={{compra.id}}>Compra: {{compra.get_folio}}</h5>
            <button class="btn-close" type="button" data-bs-dismiss ="modal" aria-label="Close"></button>
        </div>

        <div class="modal-body">
                <table class='table table-dark table striped'>
                    <thead>
                        <tr>
                        <th scope="col">Concepto</th>
                        <th scope="col">Monto</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <th scope="col">Proyecto:</th>
                            <th scope="col">{{compra.req.orden.proyecto.nombre}}</th>
                        </tr>
                        <tr>
                            <th scope="col">Subproyecto:</th>
                            <th scope="col">{{compra.req.orden.subproyecto.nombre}}</th>
                        </tr>
                        <tr>
                            <th scope="col">Presupuesto Subproyecto:</th>
                            <th scope="col" id="subproyecto" value={{compra.req.orden.subproyecto}}>{{compra.req.orden.subproyecto.presupuesto}}</th>
                        </tr>
                        <tr style="color:#3e92cc">
                            <th scope="col">Importe OC:</th>
                            <th scope="col">{{compra.costo_oc}}</th>
                        </tr>
                        {% if compra.costo_fletes > 0 %}
                        <tr style="color:#3e92cc">
                            <th scope="col">Costo Fletes:</th>
                            <th scope="col">{{compra.costo_fletes}}</th>
                        </tr>
                        <tr style="color:#3e92cc">
                            <th scope="col">Total OC:</th>
                            <th scope="col">{{costo_total}}</th>
                        </tr>
                        {% endif %}
                        <tr>
                            <th scope="col">Porcentaje Gasto/Subproyecto:</th>
                            <th scope="col"> {{porcentaje}}</th>
                        </tr>
                        <tr>
                            <th scope="col">Presupuesto remanente:*</th>
                            <th scope="col" id="resta">{{resta}}</th>
                        </tr>
                    </tbody>
                </table>
                {% if tipo_cambio %}
                <p style="color:#3e92cc">Esta OC se realizó en dólares, su valor es estimado al tipo de cambio: {{tipo_cambio}}</p>
                {% endif %}
                <table class='table table-dark table-striped'>
                    <thead>
                        <tr>
                            <th scope="col-3">#</th>
                            <th scope="col-2">Código</th>
                            <th scope="col-3">Artículos</th>
                            <th scope="col-3">Cantidad</th>
                        </tr>
                    </thead>
                    <tbody>
                    {% for producto in productos %}
                        <tr>
                            <th scope="row"><img class='row-image' src="{{producto.producto.producto.articulos.producto.producto.imageURL}}"></th>
                            <td>{{producto.producto.producto.articulos.producto.producto.codigo}}</td>
                            <td>{{producto.producto.producto.articulos.producto.producto.nombre}}</td>
                            <td>{{producto.cantidad}}</td>
                        </tr>
                   {% endfor %}
                   </tbody>
                </table>
        </div>

        <div class="modal-footer">
            <form action="{% url 'back-oc' compra.id %}" method=POST>
                {% csrf_token %}
                <div class="row my-2">
                    <div class="col-12">
                        <div class="input-group mb-3">
                            <span class="input-group-text" id="basic-addon1"><i class="fa-regular fa-message"></i></span>
                            <div class="form-floating form-floating-group flex-grow-1">   
                                {{form.comentarios|add_class:"form-control"|append_attr:"placeholder=Comentario*"}}
                                <label for="id_nombre">Comentario*</label>
                            </div>
                        </div>
                    </div>
                </div>
                <h6 style="color:yellow;">Una vez que presiones el botón de regreso la OC: {{compra.id}} quedará devuelta y se activará para ser editada</h6>
                <button class="btn btn-danger" type="submit"><i class="fa-solid fa-backward"></i></button>
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
            </form>
        </div>
    </div>

{% endblock %}

</body>
</html>