inventoryproject/urls.py
from django.contrib import admin
from django.urls import path, include
from user import views as user_view
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from user.forms import EmailLoginForm


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('dashboard.urls')),
    path('solicitudes/', include('solicitudes.urls')),
    path('requisiciones/', include('requisiciones.urls')),
    path('compras/', include('compras.urls')),
    path('entradas/', include('entradas.urls')),
    path('tesoreria/', include('tesoreria.urls')),
    path('cobranza/', include('cobranza.urls')),
    path('viaticos/', include('viaticos.urls')),
    path('gastos/', include('gastos.urls')),
    path('activos/', include('activos.urls')),
    path('user/', include('user.urls')),
    path('register/', user_view.register, name='user-register'),
    path('profile/', user_view.profile, name='user-profile'),
    #path('', auth_views.LoginView.as_view(template_name='user/login.html'), name='user-login'),
    path('', auth_views.LoginView.as_view(template_name='user/login.html', authentication_form=EmailLoginForm), name='user-login'),
    path('password-reset/', auth_views.PasswordResetView.as_view(
        template_name='user/password_reset.html',
        email_template_name='user/password_reset_email.html',
        subject_template_name = 'user/password_reset_subject.txt'
    ), name='password-reset'),
    path('logout/', auth_views.LogoutView.as_view(template_name='user/logout.html'), name='user-logout'),
] # static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('user/edit_profile/', views.edit_profile, name='edit-profile'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(
        template_name='user/password_reset_done.html'
    ), name='password_reset_done'),
    
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='user/password_reset_confirm.html'
    ), name='password_reset_confirm'),
    
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(
        template_name='user/password_reset_complete.html'
    ), name='password_reset_complete'),
    # ...
]

viaticos/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('solicitud_viatico/', views.solicitud_viatico, name='solicitud-viatico'),
    path('viaticos/viaticos_pendientes_autorizar/', views.viaticos_pendientes_autorizar, name='viaticos-pendientes-autorizar'),
    path('viaticos/detalles_viaticos/<int:pk>', views.detalles_viaticos, name='detalles-viaticos'),
    path('viaticos/autorizar_viaticos/<int:pk>', views.autorizar_viaticos, name='autorizar-viaticos'),
    path('viaticos/solicitudes_viaticos/', views.solicitudes_viaticos, name='solicitudes-viaticos'),
    path('viaticos/cancelar_viaticos/<int:pk>', views.cancelar_viaticos, name='cancelar-viaticos'),
    path('viaticos/viaticos_autorizados/', views.viaticos_autorizados, name='viaticos_autorizados'),
    path('viaticos/asignar_montos/<int:pk>', views.asignar_montos, name='asignar-montos'),
    path('viaticos/delete_viatico/<int:pk>', views.delete_viatico, name='delete-viatico'),
    path('viaticos/viaticos_pendientes_autorizar2/', views.viaticos_pendientes_autorizar2, name='viaticos-pendientes-autorizar2'),
    path('viaticos/detalles_viaticos2/<int:pk>', views.detalles_viaticos2, name='detalles-viaticos2'),
    path('viaticos/autorizar_viaticos2/<int:pk>', views.autorizar_viaticos2, name='autorizar-viaticos2'),
    path('viaticos/cancelar_viaticos2/<int:pk>', views.cancelar_viaticos2, name='cancelar-viaticos2'),
    path('viaticos/viaticos_autorizados_pago/', views.viaticos_autorizados_pago, name='viaticos-autorizados-pago'),
    path('viaticos/viaticos_pagos/<int:pk>/', views.viaticos_pagos, name='viaticos-pagos'),
    path('viaticos/matriz_facturas_viaticos/<int:pk>/', views.matriz_facturas_viaticos, name='matriz-facturas-viaticos'),
    path('viaticos/matriz_facturas/<int:pk>', views.facturas_viaticos, name='facturas-viaticos'),
    path('viaticos/factura_viatico_edicion/<int:pk>', views.factura_viatico_edicion, name='factura-viatico-edicion'),
]

viaticos/models.py
from django.db import models
from solicitudes.models import Proyecto, Subproyecto, Operacion
from user.models import Profile
from dashboard.models import Inventario
from django.core.validators import FileExtensionValidator
import decimal

# Create your models here.

class Solicitud_Viatico(models.Model):
    folio = models.CharField(max_length=6, null=True, unique=True)
    staff = models.ForeignKey(Profile, on_delete = models.CASCADE, null=True, related_name='Crea_Viatico')
    colaborador = models.ForeignKey(Profile, on_delete = models.CASCADE, null=True, blank=True, related_name='Colaborador_viatico')
    proyecto = models.ForeignKey(Proyecto, on_delete = models.CASCADE, null=True)
    subproyecto = models.ForeignKey(Subproyecto, on_delete = models.CASCADE, null=True)
    superintendente = models.ForeignKey(Profile, on_delete = models.CASCADE, null=True, related_name='Autorizacion')
    montos_asignados = models.BooleanField(default=False)
    complete = models.BooleanField(default=False)
    pagada = models.BooleanField(default=False)
    autorizar = models.BooleanField(null=True, default=None)
    autorizar2 = models.BooleanField(null=True, default=None)
    created_at = models.DateField(null=True)
    created_at_time = models.TimeField(null=True)
    fecha_partida = models.DateField(null=True)
    fecha_retorno = models.DateField(null=True)
    lugar_partida = models.CharField(max_length=20, null=True)
    lugar_comision = models.CharField(max_length=20, null=True)
    transporte = models.CharField(max_length=40, null=True)
    hospedaje = models.BooleanField(default=False)
    comentario = models.TextField(max_length=200, null=True)
    approved_at = models.DateField(null=True)
    approved_at_time = models.TimeField(null=True)
    approved_at2 = models.DateField(null=True)
    approved_at_time2 = models.TimeField(null=True)
    facturas_completas = models.BooleanField(default=False)

    @property
    def get_total(self):
        conceptos = self.concepto_viatico_set.all()
        conceptos = conceptos.filter(completo=True)
        total = sum([concepto.get_total_parcial for concepto in conceptos])
        return total

    @property
    def monto_pagado(self):
        pagado = self.pago_set.all()
        pagado = pagado.filter(hecho = True)
        total = sum([pago.monto for pago in pagado])
        return total


class Concepto_Viatico(models.Model):
    staff = models.ForeignKey(Profile, on_delete = models.CASCADE, null=True)
    producto = models.ForeignKey(Inventario, on_delete = models.CASCADE, null=True, blank=True)
    comentario = models.CharField(max_length=75, null=True, blank=True)
    viatico = models.ForeignKey(Solicitud_Viatico, on_delete = models.CASCADE, null=True)
    cantidad = models.DecimalField(max_digits=10, decimal_places=2, null=True, default=1)
    precio = models.DecimalField(max_digits=10, decimal_places=4, null=True)
    rendimiento = models.DecimalField(max_digits=5, decimal_places=2, null=True, blank=True)
    total = models.DecimalField(max_digits=14, decimal_places=6, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    #factura_pdf = models.FileField(blank=True, null=True, upload_to='facturas',validators=[FileExtensionValidator(['pdf'])])
    #factura_xml = models.FileField(blank=True, null=True, upload_to='xml', validators=[FileExtensionValidator(['xml'])])
    completo = models.BooleanField(default=False)

    class Meta:
        unique_together =('viatico','producto',)

    @property
    def get_total_parcial(self):
        if self.producto.producto.nombre == "GASOLINA":
            if self.rendimiento == None:
                self.rendimiento = 0
            total = self.cantidad/self.rendimiento *self.precio
        else:
            total = self.cantidad * self.precio
        return total

class Viaticos_Factura(models.Model):
    concepto_viatico = models.ForeignKey(Concepto_Viatico, on_delete = models.CASCADE, null=True)
    subido_por = models.ForeignKey(Profile, on_delete = models.CASCADE, null=True)
    fecha_subido = models.DateField(null=True)
    hora_subido = models.TimeField(null=True)
    comentario = models.CharField(max_length=20, null=True, blank=True)
    hecho = models.BooleanField(default=False)
    factura_pdf = models.FileField(blank=True, null=True, upload_to='facturas',validators=[FileExtensionValidator(['pdf'])])
    factura_xml = models.FileField(blank=True, null=True, upload_to='xml', validators=[FileExtensionValidator(['xml'])])

viaticos/forms.py
from django import forms
from .models import Solicitud_Viatico, Concepto_Viatico, Viaticos_Factura
from tesoreria.models import Pago


class Solicitud_ViaticoForm(forms.ModelForm):
    class Meta:
        model = Solicitud_Viatico
        fields = ['proyecto','subproyecto','superintendente','fecha_partida','fecha_retorno','colaborador','lugar_partida','lugar_comision','hospedaje','transporte','comentario']

class Concepto_ViaticoForm(forms.ModelForm):

    class Meta:
        model = Concepto_Viatico
        fields = ['producto','comentario','cantidad','precio','rendimiento','viatico']

class Pago_Viatico_Form(forms.ModelForm):
    class Meta:
        model = Pago
        fields = ['monto','comprobante_pago','cuenta']

class Viaticos_Factura_Form(forms.ModelForm):
    class Meta:
        model = Viaticos_Factura
        fields = ['factura_pdf','factura_xml','comentario']

templates/viaticos/asignar_montos.html
{% extends 'partials/base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% load widget_tweaks %}
<html>
<head>
{% block title %}Asignar Montos{% endblock %}
</head>
<body>
{% block content %}
<hr>
<hr>
<hr>
<hr>
<!-- Esta es la zona donde se crean los mensajes excitantes con sweet alert -->
<div class="row my-4">
    <div class="col-md-4">
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
        {% if messages %}
            {% for message in messages %}
                {% if message.tags == "error" %}
                <script>
                Swal.fire({
                    "title":"Error",
                    "text":"{{message}}",
                    "icon":"error",
                })
                </script>
                {% else %}
                <script>
                Swal.fire({
                    "title":"Excelente",
                    "text":"{{message}}",
                    "icon":"success",
                })
                </script>
                {% endif %}
            {% endfor %}
        {% endif %}
    </div>
</div>
<div class="row">
    <div class="col-lg-6">
        <div class="box-element" id="form-wrapper">
            <h3 id='viatico' solicitud={{viatico.id}}>Viáticos Folio: {{viatico.id}}</h3>
            <div id="Solicitud-info">
                <table class='table table striped'>
                    <thead>
                        <tr>
                        <th scope="col"><i class="fa-solid fa-person-walking-luggage"></i> Viatico para:</th>
                        <th scope="col">{{viatico.colaborador.staff.first_name}} {{viatico.colaborador.staff.last_name}}</th>
                        </tr>
                    </thead>
                    <tbody>
                    <tr>
                        <th scope="col"><i class="fa-solid fa-ranking-star"></i> Nivel:</th>
                        <th scope="col">{{viatico.proyecto.nivel}}</th>
                    </tr>
                    <tr>
                        <th scope="col"><i class="fa-solid fa-diagram-project"></i> Proyecto:</th>
                        <th scope="col">{{viatico.proyecto.nombre}}</th>
                    </tr>
                    <tr>
                        <th scope="col"><i class="fa-solid fa-diagram-project"></i> Subproyecto:</th>
                        <th scope="col">{{viatico.subproyecto.nombre}}</th>
                    </tr>
                    <tr>
                        <th scope="col"><i class="fa-regular fa-calendar-days"></i> Fecha de Partida:</th>
                        <th scope="col">{{viatico.fecha_partida}}</th>
                    </tr>
                    <tr>
                        <th scope="col"><i class="fa-regular fa-calendar-days"></i> Fecha de Retorno:</th>
                        <th scope="col">{{viatico.fecha_retorno}}</th>
                    </tr>
                    <tr>
                        <th scope="col"><i class="fa-solid fa-location-dot"></i> Lugar de Partida:</th>
                        <th scope="col">{{viatico.lugar_partida}}</th>
                    </tr>
                    <tr>
                        <th scope="col"><i class="fa-solid fa-route"></i> Lugar de Comisión:</th>
                        <th scope="col">{{viatico.lugar_comision}}</th>
                    </tr>
                    <tr>
                        <th scope="col"><i class="fa-solid fa-car-side"></i> Transporte:</th>
                        <th scope="col">{{viatico.transporte}}</th>
                    </tr>
                    <tr>
                        <th scope="col"><i class="fa-solid fa-hotel"></i> Hospedaje:</th>
                        {% if viatico.hospedaje %}
                        <th scope="col">Sí</th>
                        {% else %}
                        <th>No</th>
                        {% endif %}
                    </tr>
                    <tr>
                        <th scope="col"><i class="fa-solid fa-comment"></i> Comentario</th>
                        <th scope="col">{{viatico.comentario}}</th>
                    </tr>
                    </tbody> 
                </table>
                <form method="post">
                    {% csrf_token %}
                <input class="btn btn-outline-info btn-lg btn-block my-2" name="btn_asignar" id="btn_asignar" type="submit" value="Asignar"> 
                </form>
            </div>
        </div>
    </div>
    <div class="col-lg-6">
        <div class="box-element">
            <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% if error_messages %}
            <div class="alert alert-danger" role="alert">
                {{error_messages}}
            </div>
            {% endif %}
            <div class="row-3">
                    <label for="form.producto" id="lbl_producto"><strong>Concepto:*</strong></label>
                    {{form.producto|add_class:"form-control"}}
            </div>
            <div class="row-3">
                    <label for="form.cantidad" id="lbl_cantidad"><strong>Cantidad:*</strong></label>
                    {{form.cantidad|add_class:"form-control"}}
            </div>
            <div class="row-3">
                <label for="form.precio" id="lbl_precio"><strong>Precio Unitario:*</strong></label>
                {{form.precio|add_class:"form-control"}}
            </div>
            <div id="rendimiento" class="row-3 d-none">
                <label for="id_lugar_partida"><strong>Rendimiento(km/l):*</strong></label>
                {{form.rendimiento|add_class:"form-control"}}
            </div>
            <div id="rendimiento" class="row-3">
                <label for="id_lugar_partida"><strong>Comentario:</strong></label>
                {{form.comentario|add_class:"form-control"}}
            </div>
            <div id="rendimiento" class="row-3 d-none">
                <label for="id_lugar_partida"><strong>Viatico:</strong></label>
                {{form.viatico|add_class:"form-control"}}
            </div>
            <div  class="row">
                <div class="col-sm-1">
                    <input class="btn btn-outline-info btn-block my-2" name="btn_producto" id="btn_producto" type="submit" value="Agregar"> 
                </div>
            </div>
            </form>
            <hr>
            <table class="table table-light table-striped table-hover mx-2">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Producto</th>
                    <th scope="col">Cantidad</th>
                    <th scope="col">P.U.</th>
                    <th scope="col">Total</th>
                    <th scope="col" class="col-sm-2">Acción</th>
                </tr>
            </thead>
            <tbody id="mytbl">
                {% for producto in conceptos%}
            
                <tr>
                    <td scope="col">{{producto.producto.producto.codigo}}</td>
                    <td scope="col">{{producto.producto.producto.nombre}}</td>
                    <td scope="col">{{producto.cantidad}}</td>
                    <td scope="col">${{producto.precio|floatformat:2}}</td>
                    <td scope="col">${{producto.get_total_parcial|floatformat:2}}</td></td>
                    <td scope="col"><a type="button" class="btn btn-danger" value="Delete" name="btn_delete" id="delete" href="{% url 'delete-viatico' producto.id %}" aria-label="Close"><i class="fa-solid fa-trash-can"></i></a>
                </tr>
                {% endfor %}
            </tbody>
            </table>
            <table class="table table-light table-striped mx-1">
            <thead>
                <tr>
                    <th scope="col">Total</th>
                    <td scope="col" id="total">${{viatico.get_total|floatformat:2}}</td>
                </tr>
            </tbody>
            </table>
        </div>
    </div>
    <div class="modal fade" id ="dialog" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" role="dialog">
        <div class="modal-dialog modal-lg modal-dialog-centered" id="document" role="document" hx-target="this">

        </div>
    </div>
</div>
<!--AJAX CALL-->
  <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
  <script>

    ;(function(){
    const modal = new bootstrap.Modal(document.getElementById('dialog'))

    htmx.on('htmx:beforeSwap',(e)=>{
        if (e.detail.target.id === "document" && !e.detail.xhr.response)
        modal.hide()
    })
    })()

    var myModal = document.getElementById('dialog')

    myModal.addEventListener('hidden.bs.modal', function (event) {
    location.reload();
    })

    viatico = document.getElementById('id_viatico')
    via_id = document.getElementById('viatico')
    id_via = via_id.getAttribute('solicitud')


    viatico.value= id_via


    document.getElementById("id_producto").addEventListener("change", (event)=>{
    var select = document.getElementById("id_producto");
    var rendimiento = document.getElementById('rendimiento')
    var lbl_cantidad = document.getElementById('lbl_cantidad')
    
    console.log(lbl_cantidad)
    if (select.value == '795'){
        rendimiento.setAttribute('class','row-3')
        lbl_cantidad.innerHTML = '<strong>Kilometraje:*</strong>'
    } else {
        rendimiento.setAttribute('class','row-3 d-none')
        lbl_cantidad.innerHTML = '<strong>Cantidad:*</strong>'
    }
});

document.getElementById("btn_producto").addEventListener("click",(event)=>{
    var rendimiento = document.getElementById('id_rendimiento')
    var select = document.getElementById("id_producto");
    console.log(rendimiento.value)

   

    if (select.value == '795'){
        if (!rendimiento.value){
            event.preventDefault() 
        }
    }

});

   
   
   
</script>
{% endblock %}
</body>
</html>

templates/viaticos/solicitudes_viaticos.html
{% extends 'partials/base.html' %}
{% load crispy_forms_tags %}
{% load widget_tweaks %}
{% load static %}
{% load tt_extras %}
<html>
<head>
{% block title %}Viáticos{% endblock %}
</head>
<body>
{% block content %}
<hr>
<hr>
<h6>&nbsp;</h6>
<h6>&nbsp;</h6>
<div class="col-12">
    <div class="card">
        <div class="card-header">
        <h5>Filtro de Viáticos</h5>
        </div>
        <div class="card-body">
       
        <form method="GET">
            {% csrf_token %}
        <div class="row g-12">
            <div class="col-lg-4">
                <div class="input-group mb-3">
                    <span class="input-group-text" id="basic-addon1"><i class="fa-solid fa-gear"></i></span>
                    <div class="form-floating form-floating-group flex-grow-1">   
                        {{myfilter.form.id|add_class:"form-control"|append_attr:"placeholder=Folio"}}
                        <label for="id_lugar_partida">Folio</label>
                    </div>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="input-group mb-3">
                    <span class="input-group-text" id="basic-addon1"><i class="fa-solid fa-gear"></i></span>
                    <div class="form-floating form-floating-group flex-grow-1">   
                        {{myfilter.form.proyecto|add_class:"form-control"|append_attr:"placeholder=Proyecto"}}
                        <label for="id_proyecto">Proyecto</label>
                    </div>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="input-group mb-3">
                    <span class="input-group-text" id="basic-addon1"><i class="fa-solid fa-gear"></i></span>
                    <div class="form-floating form-floating-group flex-grow-1">   
                        {{myfilter.form.proyecto|add_class:"form-control"|append_attr:"placeholder=Subproyecto"}}
                        <label for="id_subproyecto">Subproyecto</label>
                    </div>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="input-group mb-3">
                <span class="input-group-text" id="basic-addon1"><i class="fa-regular fa-calendar"></i></span>
                    <div class="form-floating form-floating-group flex-grow-1">   
                        {% render_field myfilter.form.start_date type="date" class="form-control" %}
                    <label style="color: #121212;" for="id_subproyecto">Desde:</label>
                    </div>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="input-group mb-3">
                <span class="input-group-text" id="basic-addon1"><i class="fa-regular fa-calendar"></i></span>
                    <div class="form-floating form-floating-group flex-grow-1">   
                        {% render_field myfilter.form.end_date type="date" class="form-control" %}
                    <label style="color: #121212;" for="id_subproyecto">Hasta:</label>
                    </div>
                </div>
            </div>
            <div class="col-2">
                <button class="btn btn-outline-success btn-block m-3" type="submit" value="Buscar"><i class="fa-solid fa-magnifying-glass"></i></button>
            </div>
        </div>
        </form>
                <hr>
                <div class = "row mt-2 bg-white">
                    <form method=POST>
                        {% csrf_token %}
                    <ul class="nav nav-pills">
                        <!--<li class="nav-item mx-2">
                            <a class="btn btn-outline-secondary" href="{% url 'solicitud-product-selection' %}"><i class="fa-solid fa-angle-left"></i> Volver a solicitud elegir productos</a>
                        </li> -->
                        <li class="nav-item mx-2">
                            <button type="submit" class="btn btn-outline-success" name="btnExcel"><i class="fa-solid fa-file-excel fa-2xl"></i></button>
                        </li>
                        <li class="nav-item mx-2">
                            <button type="button" class="btn btn-outline-danger"><i class="fa-solid fa-file-pdf fa-2xl"></i></button>
                        </li>
                        <li class="nav-item mx-2">
                            <a class="btn btn-outline-info" href="{% url 'solicitud-matriz-productos' %}">Productos</a>
                        </li>
                    </ul>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="row my-4">
    <div class="col-md-4">
        {% for message in messages %}
            {% if message %}
            <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
            <script>
                var m = "{{ message }}";
                swal("Excelente !", m, "success")
            </script>
            {% endif %}
        {% endfor %}
    </div>
</div>
<div class = "row mt-2">
    <div class="col-md-10">
        <table class="table bg-white">
            <thead class="text-black" style="background-color: #F5F5F5;">
                <tr>
                    <th scope="col">Folio</th>
                    <th scope="col">Solicitado por:</th>
                    <th scope="col">Solicitado para:</th>
                    <th>Autorización Gerencia</th>
                    <th scope="col">Autorización N1</th>
                    <th scope="col">Proyecto</th>
                    <th scope="col">Subproyecto</th>
                    <th scope="col">Creado</th>
                    <th scope="col">Detalles</th>
                </tr>
            </thead>
            <tbody>
                {% for orden in ordenes_list %}
                <tr>
                    <th scope="row">{{orden.id}}</th>
                    <td>{{orden.staff.staff.first_name}} {{orden.staff.staff.last_name}}</td>
                    <td>{{orden.colaborador.staff.first_name}} {{orden.colaborador.staff.first_name}}</td>
                    <td>Selene Villanueva
                        {% if orden.autorizar2 == True%}|Autorizado
                        {% elif orden.autorizar2 == False %}| Cancelado
                        {% else %}| No autorizado {% endif %}
                    </td>
                    <td>{{orden.superintendente.staff.first_name}} {{orden.superintendente.staff.last_name}}
                        {% if orden.autorizar == True %}| Autorizado
                        {% elif orden.autorizar == False %}| Cancelado
                        {% else %}| No autorizado {% endif %}
                    </td>
                    <td>{{orden.proyecto.nombre}}</td>
                    <td>{{orden.subproyecto.nombre}}</td>
                    <td>{{orden.created_at}}</td>
                    <td>
                        <a id="myBtn" type="button" class="btn btn-outline-info btn-lg" data-bs-toggle="modal" data-bs-target='#dialog' hx-target="#document" hx-get="{% url 'detalles-viaticos' orden.id %}">
                            <i class="fa-solid fa-person-walking-luggage"></i>
                        </a>
                    </td>
                </tr>
                {% endfor %}
                </tbody>
        </table>
        <nav aria-label="Page navigation example">
            <ul class="pagination justify-content-center">
                {% if ordenes_list.has_previous %}
                <li class="page-item"><a class="page-link" style="color:#3E92CC" href="{% my_url ordenes_list.previous_page_number 'page' request.GET.urlencode %}"><i class="fa-solid fa-angle-left"></i></a></li>
                {% endif %}
                {% for page in ordenes_list.paginator  %}
                {% if ordenes_list.number == page.number %}
                <li class="page-item active" aria-current="page"><a class="page-link" style="background-color:#3E92CC; border-color:#3E92CC" href="?page={{page.number}}" id={{page.number}}>{{page.number}}</a></li>
                {% else %}
                <li class="page-item"><a class="page-link" style="color:#3E92CC" href="?page={{page.number}}" id={{page.number}}>{{page.number}}</a></li>
                {% endif %}
                {% endfor %}
                {% if ordenes_list.has_next %}
                <li class="page-item"><a class="page-link" style="color:#3E92CC" href="{% my_url ordenes_list.next_page_number 'page' request.GET.urlencode %}"><i class="fa-solid fa-angle-right"></i></a></li>
                {% endif %}
            </ul>
        </nav>
    </div>
</div>

<!--Este es el modal-->
<div class="modal fade" id ="dialog" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-lg" id="document" role="document" hx-target="this">

    </div>
</div>

<!--AJAX CALL-->
<script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
<script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<script>
;(function(){
    const modal = new bootstrap.Modal(document.getElementById('dialog'))

    htmx.on('htmx:beforeSwap',(e)=>{
        if (e.detail.target.id === "document" && !e.detail.xhr.response)
        modal.hide()
    })
})()
var myModal = document.getElementById('dialog')

myModal.addEventListener('hidden.bs.modal', function (event) {
  location.reload();
})


</script>
{% endblock %}
</body>
</html>