entradas/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('entradas/pendientes_entrada', views.pendientes_entrada, name='pendientes-entrada'),
    path('entradas/pendientes_entrada/articulos/<int:pk>', views.articulos_entrada, name='articulos_entrada'),
    path('entradas/pendientes_recepcion/articulos/<int:pk>', views.articulos_recepcion, name='articulos_recepcion'),
    #path('update_entrada/', views.update_entrada, name='update-entrada'),
    path('update_recepcion/', views.update_recepcion_articulos, name='update-recepcion'),
    path('entradas/pendientes_calidad', views.pendientes_calidad, name='pendientes_calidad'),
    path('entradas/pendientes_calidad/reporte/<int:pk>', views.reporte_calidad, name='reporte_calidad'),
    path('entradas/devolucion_a_proveedor/', views.devolucion_a_proveedor, name='devolucion_a_proveedor'),
    path('entradas/no_conformidad/<int:pk>', views.no_conformidad, name='no-conformidad'),
    path('entradas/productos/<int:pk>', views.productos, name="productos"),
    path('no_conformidad/', views.update_no_conformidad, name="update_no_conformidad"),
    path('entradas/recepcion', views.pendientes_recepcion, name='pendientes-recepcion'),
    path('entradas/recepcion_servicios', views.recepcion_servicios, name='recepcion-servicios'),
    path('entradas/articulos_recepcion_servicios/<int:pk>', views.articulos_recepcion_servicios, name='articulos-recepcion-servicios'),
    path('update_cantidad/', views.update_cantidad, name='update_cantidad'),
]

inventoryproject/urls.py
from django.contrib import admin
from django.urls import path, include
from user import views as user_view
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from user.forms import EmailLoginForm


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('dashboard.urls')),
    path('solicitudes/', include('solicitudes.urls')),
    path('requisiciones/', include('requisiciones.urls')),
    path('compras/', include('compras.urls')),
    path('entradas/', include('entradas.urls')),
    path('tesoreria/', include('tesoreria.urls')),
    path('cobranza/', include('cobranza.urls')),
    path('viaticos/', include('viaticos.urls')),
    path('gastos/', include('gastos.urls')),
    path('activos/', include('activos.urls')),
    path('user/', include('user.urls')),
    path('register/', user_view.register, name='user-register'),
    path('profile/', user_view.profile, name='user-profile'),
    #path('', auth_views.LoginView.as_view(template_name='user/login.html'), name='user-login'),
    path('', auth_views.LoginView.as_view(template_name='user/login.html', authentication_form=EmailLoginForm), name='user-login'),
    path('password-reset/', auth_views.PasswordResetView.as_view(
        template_name='user/password_reset.html',
        email_template_name='user/password_reset_email.html',
        subject_template_name = 'user/password_reset_subject.txt'
    ), name='password-reset'),
    path('logout/', auth_views.LogoutView.as_view(template_name='user/logout.html'), name='user-logout'),
] # static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('user/edit_profile/', views.edit_profile, name='edit-profile'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(
        template_name='user/password_reset_done.html'
    ), name='password_reset_done'),
    
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='user/password_reset_confirm.html'
    ), name='password_reset_confirm'),
    
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(
        template_name='user/password_reset_complete.html'
    ), name='password_reset_complete'),
    # ...
]

gastos/models.py
from django.db import models
from solicitudes.models import Proyecto, Subproyecto, Operacion
from dashboard.models import Inventario
from user.models import Profile
from django.core.validators import FileExtensionValidator
import decimal
import xml.etree.ElementTree as ET
import os
# Create your models here.

#Este modelo se refiere a si es Gasto o Reembolso
class Tipo_Gasto(models.Model):
    tipo = models.CharField(max_length=15, null=True)

    def __str__(self):
        return f'{self.id}:{self.tipo}'

class Solicitud_Gasto(models.Model):
    folio = models.CharField(max_length=6, null=True, unique=True)
    staff = models.ForeignKey(Profile, on_delete = models.CASCADE, null=True, related_name='Crea_gasto')
    colaborador = models.ForeignKey(Profile, on_delete=models.CASCADE,null=True, related_name='Asignado_gasto', blank=True)
    #proyecto = models.ForeignKey(Proyecto, on_delete = models.CASCADE, null=True)
    #subproyecto = models.ForeignKey(Subproyecto, on_delete = models.CASCADE, null=True)
    area = models.ForeignKey(Operacion, on_delete = models.CASCADE, null=True, blank=True)
    superintendente = models.ForeignKey(Profile, on_delete = models.CASCADE, null=True, related_name='superintendente')
    complete = models.BooleanField(null=True)
    tipo = models.ForeignKey(Tipo_Gasto, on_delete=models.CASCADE, null=True)
    pagada = models.BooleanField(default=False)
    autorizar = models.BooleanField(null=True, default=None)
    autorizar2 = models.BooleanField(null=True, default=None)
    created_at = models.DateField(null=True)
    created_at_time = models.TimeField(null=True)
    approved_at = models.DateField(null=True)
    approved_at_time = models.TimeField(null=True)
    approbado_fecha2 = models.DateField(null=True)
    approved_at_time2 = models.TimeField(null=True)
    facturas_completas = models.BooleanField(default=False)

    @property
    def get_validado(self):
        productos = self.articulo_gasto_set.all()
        productos = productos.filter(producto__producto__nombre="MATERIALES", completo=True, validacion = False, gasto__tipo__tipo = "REEMBOLSO")
        conteo_productos = productos.count()
        if productos == None:
            valor = True
        else:
            if conteo_productos == 0:
                valor = True
            else:
                valor = False
            
        return valor

    @property
    def monto_pagado(self):
        pagado = self.pago_set.all()
        pagado= pagado.filter(hecho=True)
        total = sum([pago.monto for pago in pagado])
        return total

    @property
    def get_subtotal_solicitud(self):
        productos = self.articulo_gasto_set.all()
        productos = productos.filter(completo=True)
        total = sum([producto.get_subtotal for producto in productos])
        return total

    @property
    def get_total_impuesto(self):
        productos = self.articulo_gasto_set.all()
        productos = productos.filter(completo=True)
        suma = round(sum([(producto.get_iva + producto.get_otros_impuestos) for producto in productos]),2)
        return suma

    @property
    def get_total_solicitud(self):
        productos = self.articulo_gasto_set.all()
        productos = productos.filter(completo=True)
        total = sum([producto.total_parcial for producto in productos])
        return total

    def __str__(self):
        return f'{self.id}'

class Articulo_Gasto(models.Model):
    staff = models.ForeignKey(Profile, on_delete = models.CASCADE, null=True)
    clase = models.BooleanField(null=True, default=False)   #Se refiere a si el producto es del True == almacén o entrara al almacén o si va por fuera
    producto = models.ForeignKey(Inventario, on_delete = models.CASCADE, null=True, blank=True)
    comentario = models.CharField(max_length=75, null=True)
    descripcion = models.CharField(max_length=300, null=True)
    otros_impuestos = models.DecimalField(default=0,max_digits=14, decimal_places=4, null=True, blank=True)
    impuestos_retenidos = models.DecimalField(default=0, max_digits=14, decimal_places=4, null=True, blank=True)
    gasto = models.ForeignKey(Solicitud_Gasto, on_delete = models.CASCADE, null=True)
    cantidad = models.DecimalField(max_digits=10, decimal_places=6, null=True, blank=True)
    precio_unitario = models.DecimalField(max_digits=14, decimal_places=6, null=True, blank=True)
    entrada_salida_express = models.BooleanField(null=True, default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    factura_pdf = models.FileField(blank=True, null=True, upload_to='facturas',validators=[FileExtensionValidator(['pdf'])])
    factura_xml = models.FileField(blank=True, null=True, upload_to='xml', validators=[FileExtensionValidator(['xml'])])
    completo = models.BooleanField(default=False)
    validacion = models.BooleanField(default=False)
    proyecto = models.ForeignKey(Proyecto, on_delete = models.CASCADE, null=True)
    subproyecto = models.ForeignKey(Subproyecto, on_delete = models.CASCADE, null=True)

    def __str__(self):
        return f'{self.producto}'
    
    @property
    def emisor(self):
        #with open(self.factura_xml.path,'r') as file:
            #data = file.read()
        tree = ET.parse(self.factura_xml.path)
        root = tree.getroot()
        ns = {'cfdi':'http://www.sat.gob.mx/cfd/4'}
        #comprobante = root.findall('cfdi:Comprobante')
        emisor = root.find('cfdi:Emisor', ns)
        receptor = root.find('cfdi:Receptor', ns)
        impuestos = root.find('cfdi:Impuestos', ns)
        conceptos = root.find('cfdi:Conceptos', ns)
        resultados = []
        for concepto in conceptos.findall('cfdi:Concepto', ns):
            descripcion = concepto.get('Descripcion')
            cantidad = concepto.get('Cantidad')
            precio = concepto.get('ValorUnitario') 
            # Aquí agrupamos los valores en una tupla antes de añadirlos a la lista
            resultados.append((descripcion, cantidad, precio))
        # Obtener los datos requeridos
        rfc = emisor.get('Rfc')
        nombre = emisor.get('Nombre')
        regimen_fiscal = emisor.get('RegimenFiscal')
        total = root.get('Total')
        subtotal = root.get('Subtotal')
        impuestos = root.get('TotalImpuestosTrasladados')


        return {'rfc': rfc, 'nombre': nombre, 'regimen_fiscal': regimen_fiscal,'total':total,'resultados':resultados}

    @property
    def get_subtotal(self):
        subtotal = 0
        if self.precio_unitario and self.cantidad:
            subtotal = round(self.precio_unitario * self.cantidad, 2)
        return subtotal

    @property
    def get_iva(self):
        iva = 0

        if self.precio_unitario and self.cantidad:
            iva = self.precio_unitario * decimal.Decimal(str(0.16))*self.cantidad
        else:
            iva = 0
        return iva

    @property
    def get_otros_impuestos(self):
        impuestos = 0
        if self.otros_impuestos:
            if self.impuestos_retenidos:
                impuestos = round(self.otros_impuestos - self.impuestos_retenidos, 2)
            else:
                impuestos = round(self.otros_impuestos,2)
        else:
            if self.impuestos_retenidos:
                impuestos = round(-self.impuestos_retenidos, 2)


        return impuestos

    @property
    def total_parcial(self):
        impuesto = self.get_iva
        total = round(self.get_subtotal + impuesto + self.get_otros_impuestos)
        return total

class Factura(models.Model):
    solicitud_gasto = models.ForeignKey(Solicitud_Gasto, on_delete=models.CASCADE, related_name='facturas', null=True)
    archivo_pdf = models.FileField(upload_to='facturas', validators=[FileExtensionValidator(['pdf'])])
    archivo_xml = models.FileField(blank=True, null=True, upload_to='xml', validators=[FileExtensionValidator(['xml'])])
    fecha_subida= models.DateTimeField(null=True, blank=True)
    # Puedes agregar más campos si es necesario, como fecha, descripción, etc.

    @property
    def emisor(self):
        tree = None
        try:
            tree = ET.parse(self.archivo_xml.path)
        except ET.ParseError as e:
            print(f"Error al parsear el archivo XML: {e}")
        #tree = ET.parse(self.archivo_xml.path)
        if tree is not None:
            root = tree.getroot()
            ns = {'cfdi':'http://www.sat.gob.mx/cfd/4'}
            emisor = root.find('cfdi:Emisor', ns)
            receptor = root.find('cfdi:Receptor', ns)
            impuestos = root.find('cfdi:Impuestos', ns)
            conceptos = root.find('cfdi:Conceptos', ns)
            resultados = []

            if conceptos is not None:
                for concepto in conceptos.findall('cfdi:Concepto', ns):
                    descripcion = concepto.get('Descripcion')
                    cantidad = concepto.get('Cantidad')
                    precio = concepto.get('ValorUnitario') 
                    resultados.append((descripcion, cantidad, precio))
            else:
                resultados = "El archivo parace no tener el formato correcto"

            rfc = emisor.get('Rfc') if emisor is not None else "No disponible"
            nombre = emisor.get('Nombre') if emisor is not None else "No disponible"
            regimen_fiscal = emisor.get('RegimenFiscal') if emisor is not None else "No disponible"
            total = root.get('Total') if root is not None else "No disponible"
            subtotal = root.get('Subtotal') if root is not None else "No disponible"
            impuestos = root.get('TotalImpuestosTrasladados') if root is not None else "No disponible"

            return {'rfc': rfc, 'nombre': nombre, 'regimen_fiscal': regimen_fiscal, 'total': total, 'resultados': resultados}
        else:
            resultados = "El archivo parace no tener el formato correcto"

        
    
class Entrada_Gasto_Ajuste(models.Model):
    gasto = models.ForeignKey(Articulo_Gasto, on_delete = models.CASCADE, null=True, blank=True)

user/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Banco(models.Model):
    nombre = models.CharField(max_length=50, null=True)

    def __str__(self):
        return f'{self.nombre}'

class Tipo_perfil(models.Model):
    #Nombre
    nombre = models.CharField(max_length=200, null=True)
    #Filtros del nav
    inicio_estadisticas = models.BooleanField(null=True, default=False)
    calidad = models.BooleanField(null=True, default=False)
    configuracion = models.BooleanField(null=True, default=False)
    almacen = models.BooleanField(null=True, default=False)
    solicitudes = models.BooleanField(null=True, default=False)
    requisiciones = models.BooleanField(null=True, default=False)
    compras = models.BooleanField(null=True, default=False)
    tesoreria = models.BooleanField(null=True, default=False)
    autorizacion = models.BooleanField(null=True, default=False)
    reportes = models.BooleanField(null=True, default=False)
    historicos = models.BooleanField(null=True, default=False)
    proveedores = models.BooleanField(null=True, default=False)
    #Filtros de perfil para acciones
    supervisor = models.BooleanField(null=True, default=False)
    superintendente = models.BooleanField(null=True, default=False)
    almacenista = models.BooleanField(null=True, default=False)
    comprador = models.BooleanField(null=True, default=False)
    oc_superintendencia = models.BooleanField(null=True, default=False)
    oc_gerencia = models.BooleanField(null=True, default=False)
    def __str__(self):
        return f'{self.nombre}'

class Distrito(models.Model):
    nombre = models.CharField(max_length=20, null=True)
    abreviado = models.CharField(max_length=3, null=True)

    def __str__(self):
        return f'{self.nombre} - {self.abreviado}'

class Almacen(models.Model):
    nombre = models.CharField(max_length=25, null=True)
    distrito = models.ForeignKey(Distrito, on_delete = models.CASCADE, null=True)

    def __str__(self):
        return f'{self.nombre}'



class Profile(models.Model):
    staff = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
    address = models.CharField(max_length=200, null=True)
    phone = models.CharField(max_length=20, null=True)
    distrito = models.ForeignKey(Distrito, on_delete=models.CASCADE, null=True)
    almacen = models.ManyToManyField(Almacen, related_name='almacenes')
    banco = models.ForeignKey(Banco, on_delete=models.CASCADE, null=True, blank=True)
    cuenta_bancaria = models.CharField(max_length=12, null=True, blank=True)
    clabe = models.CharField(max_length=18, null=True, blank=True)
    image = models.ImageField(blank=True, upload_to='profile_images')
    tipo = models.ForeignKey(Tipo_perfil, on_delete = models.CASCADE, null=True)
    nivel = models.PositiveSmallIntegerField(default=4)

    def __str__(self):
        return f'{self.staff.username}'

    @property
    def imageURL(self):
        try:
            url = self.image.url
        except:
            url = ''
        return url

entradas/forms.py
from django import forms
from .models import Entrada, EntradaArticulo, Reporte_Calidad, No_Conformidad, NC_Articulo

class EntradaArticuloForm(forms.ModelForm):
    class Meta:
        model = EntradaArticulo
        fields = ['cantidad','referencia']

class Reporte_CalidadForm(forms.ModelForm):
    class Meta:
        model = Reporte_Calidad
        fields = ['cantidad','comentarios','evaluacion']

class NoConformidadForm(forms.ModelForm):
    class Meta:
        model = No_Conformidad
        fields = ['comentario']

class NC_ArticuloForm(forms.ModelForm):
    class Meta:
        model = NC_Articulo
        fields = ['articulo_comprado','cantidad']

templates/entradas/pendientes_recepcion.html
{% extends 'partials/base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% load widget_tweaks %}
{% load tt_extras %}
<html>
<head>
{% block title %}Recepciones Pendientes{% endblock %}
</head>
<body>
{% block content %}
<hr>
<hr>
<hr>
<h6>&nbsp;</h6>
<h6 class="d-lg-none">&nbsp;</h6>
<div class = "col bg-white" id="response-div">
    <div class="card">
        <div class="card-header">
            <h5>Pendientes de Recepción</h5>
        </div>
        <div class="card-body">
            {% csrf_token %}
            <form method="GET">
            <div class="row">
                <div class="col-lg-3 col-sm-12">
                    <div class="input-group mb-3">
                    <span class="input-group-text" id="basic-addon1"><i class="fa-solid fa-hashtag"></i></span>
                        <div class="form-floating form-floating-group flex-grow-1">   
                            {{myfilter.form.id|add_class:"form-control"|append_attr:"placeholder= Folio OC"}}
                            <label style="color: #121212;" for="id_staff">Folio OC</label>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-sm-12">
                    <div class="input-group mb-3">
                    <span class="input-group-text" id="basic-addon1"><i class="fa-solid fa-user"></i></span>
                        <div class="form-floating form-floating-group flex-grow-1">   
                            {{myfilter.form.proveedor|add_class:"form-control"|append_attr:"placeholder= Proveedor"}}
                            <label style="color: #121212;" for="id_staff">Proveedor</label>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-sm-12">
                    <div class="input-group mb-3">
                    <span class="input-group-text" id="basic-addon1"><i class="fa-solid fa-hashtag"></i></span>
                        <div class="form-floating form-floating-group flex-grow-1">   
                            {{myfilter.form.req|add_class:"form-control"|append_attr:"placeholder= Requisición"}}
                            <label style="color: #121212;" for="id_staff">Requisición</label>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-sm-12">
                    <div class="input-group mb-3">
                    <span class="input-group-text" id="basic-addon1"><i class="fa-solid fa-diagram-project"></i></span>
                        <div class="form-floating form-floating-group flex-grow-1">   
                            {{myfilter.form.proyecto|add_class:"form-control"|append_attr:"placeholder= Proyecto"}}
                            <label style="color: #121212;" for="id_proyecto">Proyecto</label>
                        </div>
                    </div>
                </div>       
            </div>
            <div class="row">
                <div class="col-lg-3 col-sm-12">
                    <div class="input-group mb-3">
                    <span class="input-group-text" id="basic-addon1"><i class="fa-solid fa-diagram-project"></i></span>
                        <div class="form-floating form-floating-group flex-grow-1">   
                            {{myfilter.form.subproyecto|add_class:"form-control"|append_attr:"placeholder= Subproyecto"}}
                            <label style="color: #121212;" for="id_proyecto">Subproyecto</label>
                        </div>
                    </div>
                </div>  
                <div id="serie" class="col-lg-2 col-md-auto col-sm-auto">
                    <div class="input-group mb-3">
                    <span class="input-group-text" id="basic-addon1"><i class="fa-regular fa-calendar"></i></span>
                        <div class="form-floating form-floating-group flex-grow-1">   
                            {% render_field myfilter.form.start_date type="date" class="form-control" %}
                        <label style="color: #121212;" for="id_subproyecto">Desde:</label>
                        </div>
                    </div>
                </div>
                <div id="serie" class="col-lg-2 col-md-auto col-sm-auto">
                    <div class="input-group mb-3">
                    <span class="input-group-text" id="basic-addon1"><i class="fa-regular fa-calendar"></i></span>
                        <div class="form-floating form-floating-group flex-grow-1">   
                            {% render_field myfilter.form.end_date type="date" class="form-control" %}
                        <label style="color: #121212;" for="id_subproyecto">Hasta:</label>
                        </div>
                    </div>
                </div>
                    <div class="col-2">
                        <button class="btn btn-outline-success btn-block btn-lg mt-1" type="submit" value="Buscar"><i class="fa-solid fa-magnifying-glass"></i></button>
                    </div>
                </div>
                <hr>
                </form>
                <form method=POST>
                    {% csrf_token %}
                    <!--<ul class="nav nav-pills">
                        <li class="nav-item mx-2">
                            <button type="submit" class="btn btn-outline-success" value='Reporte Excel'>
                                <i class="fa-solid fa-file-excel fa-2xl"></i>
                            </button>
                        </li>
                        <li class="nav-item mx-2">
                            <button type="button" class="btn btn-outline-danger">
                               <i class="fa-solid fa-file-pdf fa-2xl"></i>
                            </button>
                        </li>
                    </ul>-->
                </form>
            </div>
        </div>
        
    </div>
    <!-- Aquí terminan el encabezado de los filtros -->

<!-- Esta es la zona donde se crean los mensajes perrones con sweet alert -->
<div class="row my-4">
    <div class="col-md-4">
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
        {% if messages %}
            {% for message in messages %}
                {% if message.tags == "error" %}
                <script>
                Swal.fire({
                    "title":"Error",
                    "text":"{{message}}",
                    "icon":"error",
                })
                </script>
                {% else %}
                <script>
                Swal.fire({
                    "title":"Excelente",
                    "text":"{{message}}",
                    "icon":"success",
                })
                </script>
                {% endif %}
            {% endfor %}
        {% endif %}
    </div>
</div>

<div class = "col">
    <div class="card">
        <div class ="table-responsive-sm">
            <table class="table bg-white">
            <thead class="text-black" style="background-color: #F5F5F5;">
                <tr>
                    <th scope="col">Compra</th>
                    <th class="d-none d-lg-table-cell">Req.</th>
                    <th scope="col">Sol.</th>
                    <th class="d-none d-lg-table-cell">Solicitado por</th>
                    <th scope="col">Proyecto</th>
                    <th class="d-none d-lg-table-cell">Subproyecto</th>
                    <th class="d-none d-lg-table-cell">Autorizado</th>
                    <th scope="col">Proveedor</th>
                    <th scope="col">Acción</th>
                </tr>
            </thead>
            <tbody>
                {% for compra in compras_list %}
                <tr>
                    <td scope="col">{{compra.get_folio}}</th>
                    <td class="d-none d-lg-table-cell">{{compra.req.folio}}</td>
                    <td scope="col">{{compra.req.orden.folio}}</td>
                    <td class="d-none d-lg-table-cell">{{compra.req.orden.staff.staff.first_name}} {{compra.req.orden.staff.staff.last_name}}</td>
                    <td>{{compra.req.orden.proyecto.nombre}}</td>
                    <td class="d-none d-lg-table-cell">{{compra.req.orden.subproyecto.nombre}}</td>
                    <td class="d-none d-lg-table-cell">{{compra.autorizado_date2}} </td>
                    {% if compra.proveedor.nombre.razon_social == "COLABORADOR" %}
                    <td>{{compra.deposito_comprador.staff.first_name}} {{compra.deposito_comprador.staff.last_name}}</td>
                    {% else %}
                    <td>{{compra.proveedor}}</td>
                    {% endif %}
                    <td>
                        <ul class="nav nav-pills">
                            <li class="nav-item m-1">
                                <a id="myBtn" type="button" class="btn btn-outline-info" href="{% url 'articulos_recepcion' compra.id %}">Recepción</a>
                            </li>
                            <!-- Añadir el botón de productos aquí -->
                            <li class="nav-item m-1">
                            <a id="productosBtn" type="button" class="btn btn-outline-success" data-bs-toggle="modal" data-bs-target="#dialog" hx-target="#document" hx-get="{% url 'productos' compra.id %}">Productos</a>
                            </li>
                            <!-- Añadir el botón de NC aquí -->
                            <li class="nav-item m-1">
                            <a id="ncBtn" type="button" class="btn btn-outline-warning" href="{% url 'no-conformidad' compra.id %}">NC</a>
                            </li> 
                        </ul>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
            </table>

        </div>
   
    </div>
</div>
    <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-center">
            {% if compras_list.has_previous %}
                <li class="page-item"><a class="page-link" style="color:#3E92CC" href="{% my_url 1 'page' request.GET.urlencode %}"><i class="fa-solid fa-angles-left"></i></a></li>
                <li class="page-item"><a class="page-link" style="color:#3E92CC" href="{% my_url compras_list.previous_page_number  'page' request.GET.urlencode %}"><i class="fa-solid fa-angle-left"></i></a></li>
            {% endif %}

            {% for item in compras_list.paginator.page_range %}
                {% if compras_list.number == item %}
                    <li class="page-item active"><a href="#" class="page-link bg-dark">{{item}}</a></li>
                {% elif item > compras_list.number|add:'-2' and item < compras_list.number|add:'2' %}
                    <li class="page-item "><a class="page-link" style="color:#3E92CC" href="{% my_url item 'page' request.GET.urlencode %}" class="page-link">{{item}}</a></li>
                {% endif %}
            {% endfor %}

            {% if compras_list.paginator.num_pages > compras_list.number|add:'2' %}
            <li><a class="page-link" style="color:#3E92CC" href="?page={{compras_list.number|add:'2'}}">&hellip;</a></li>
            <li><a style="color:#3E92CC" href="?page={{ item }}">{{item}}</a></li>
            <li><a class="page-link" style="color:#3E92CC" href="{% my_url compras_list.paginator.num_pages 'page' request.GET.urlencode %}">{{compras_list.paginator.num_pages}}</a></li>
            {% endif %}

            {% if compras_list.has_next %}
                <li class="page-item"><a class="page-link" style="color:#3E92CC" href="{% my_url compras_list.next_page_number 'page' request.GET.urlencode %}"><i class="fa-solid fa-chevron-right"></i></a></li>
                <li class="page-item"><a class="page-link" style="color:#3E92CC" href="{% my_url compras_list.paginator.num_pages 'page' request.GET.urlencode %}"><i class="fa-solid fa-angles-right"></i></a></a></li>
            {% endif %}
        </ul>
    </nav>


<!--Este es el modal-->
<div class="modal fade" id ="dialog" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-lg" id="document" role="document" hx-target="this">

    </div>
</div>

<script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
<script>
var dataSpyList = [].slice.call(document.querySelectorAll('[data-bs-spy="scroll"]'))
dataSpyList.forEach(function (dataSpyEl) {
  bootstrap.ScrollSpy.getInstance(dataSpyEl)
    .refresh()
});
;(function(){
    const modal = new bootstrap.Modal(document.getElementById('dialog'))

    htmx.on('htmx:beforeSwap',(e)=>{
        if (e.detail.target.id === "document" && !e.detail.xhr.response)
        modal.hide()
    })
})()
var myModal = document.getElementById('dialog')

myModal.addEventListener('hidden.bs.modal', function (event) {
  location.reload();
})

</script>
{% endblock %}
</body>
</html>