dashboard/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('dashboard/', views.index, name= 'dashboard-index'),
    path('configuracion/proyectos', views.proyectos, name='configuracion-proyectos'),
    path('configuracion/subproyectos/<int:pk>', views.subproyectos, name='subproyectos'),
    path('configuracion/proyectos/editar/<int:pk>', views.proyectos_edit, name='proyectos-edit'),
    path('configuracion/proyectos/add', views.proyectos_add, name='proyectos-add'),
    path('configuracion/subproyectos_add/<int:pk>', views.subproyectos_add, name='subproyectos-add'),
    path('configuracion/subproyectos_edit/<int:pk>', views.subproyectos_edit, name='subproyectos-edit'),
    path('staff/', views.staff, name='dashboard-staff'),
    path('product/', views.product, name='dashboard-product'),
    path('product/upload_batch_products', views.upload_batch_products, name='upload_batch_products'),
    path('product/delete/<int:pk>/', views.product_delete, name='dashboard-product-delete'),
    path('product/update/<int:pk>/', views.product_update, name='dashboard-product-update'),
    path('product/add/', views.add_product, name='add-product'),
    path('proveedores/', views.proveedores, name='dashboard-proveedores'),
    path('proveeedores/matriz_comparativo', views.matriz_proveedores_comparativo, name='matriz-proveedores-comparativo'),
    path('proveedores/add/', views.add_proveedores, name='add_proveedores'),
    path('proveedores/add_nuevo/', views.add_proveedores2, name='add_proveedores2'),
    path('proveedores/add_proveedor_comparativo/', views.add_proveedores_comparativo, name='add_proveedores_comparativo'),
    path('proveedor/matriz_revision_proveedor', views.matriz_revision_proveedor, name='matriz-revision-proveedor'),
    path('proveedor/update/<int:pk>/', views.proveedores_update, name='dashboard-proveedores-update'),
    path('proveedor/direcciones/<int:pk>/', views.proveedor_direcciones, name='proveedor-direcciones'),
    path('proveedor/add_direccion/<int:pk>/', views.add_proveedor_direccion, name='add-proveedor-direccion'),
    path('proveedor/edit_direccion/<int:pk>', views.edit_proveedor_direccion, name='edit_proveedor_direccion'),
    path('proveedores/upload_batch_proveedores', views.upload_batch_proveedores, name='upload_batch_proveedores'),
    path('proveedores/upload_batch_proveedores_direcciones', views.upload_batch_proveedores_direcciones, name='upload_batch_proveedores_direcciones'),
    path('order/', views.order, name='dashboard-order'),
    path('ajax/load-subfamilias/', views.load_subfamilias, name='ajax_load_subfamilias'),  # <-- rutina en Ajax
    path('dashboard/staff_detail/<int:pk>/', views.staff_detail, name='dashboard-staff-detail'),
    #API
    path('product/revision_calidad/<int:pk>', views.revision_producto_calidad, name='revision-producto-calidad'),
]

inventoryproject/urls.py
from django.contrib import admin
from django.urls import path, include
from user import views as user_view
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from user.forms import EmailLoginForm


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('dashboard.urls')),
    path('solicitudes/', include('solicitudes.urls')),
    path('requisiciones/', include('requisiciones.urls')),
    path('compras/', include('compras.urls')),
    path('entradas/', include('entradas.urls')),
    path('tesoreria/', include('tesoreria.urls')),
    path('cobranza/', include('cobranza.urls')),
    path('viaticos/', include('viaticos.urls')),
    path('gastos/', include('gastos.urls')),
    path('activos/', include('activos.urls')),
    path('user/', include('user.urls')),
    path('register/', user_view.register, name='user-register'),
    path('profile/', user_view.profile, name='user-profile'),
    #path('', auth_views.LoginView.as_view(template_name='user/login.html'), name='user-login'),
    path('', auth_views.LoginView.as_view(template_name='user/login.html', authentication_form=EmailLoginForm), name='user-login'),
    path('password-reset/', auth_views.PasswordResetView.as_view(
        template_name='user/password_reset.html',
        email_template_name='user/password_reset_email.html',
        subject_template_name = 'user/password_reset_subject.txt'
    ), name='password-reset'),
    path('logout/', auth_views.LogoutView.as_view(template_name='user/logout.html'), name='user-logout'),
] # static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('user/edit_profile/', views.edit_profile, name='edit-profile'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(
        template_name='user/password_reset_done.html'
    ), name='password_reset_done'),
    
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='user/password_reset_confirm.html'
    ), name='password_reset_confirm'),
    
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(
        template_name='user/password_reset_complete.html'
    ), name='password_reset_complete'),
    # ...
]

dashboard/models.py
from django.db import models
# De django.contrib.auth.models estamos importando el modelo de usuarios de la administration
from user.models import Distrito, Profile, Almacen
from solicitudes.models import Proyecto, Subproyecto, Operacion
#from djmoney.models.fields import MoneyField
from simple_history.models import HistoricalRecords
from django.core.validators import FileExtensionValidator
#from django.db.models.functions import TruncDate

# Create your models here.





class Familia(models.Model):
    nombre = models.CharField(max_length=40, null=True, unique=True)

    def __str__(self):
        return f'{self.nombre}'

class Unidad(models.Model):
    nombre = models.CharField(max_length=10, null=True, unique=True)

    def __str__(self):
        return f'{self.nombre}'

class Subfamilia(models.Model):
    nombre = models.CharField(max_length=30, null=True)
    familia = models.ForeignKey(Familia, on_delete = models.CASCADE, null=True)

    def __str__(self):
        return f'{self.nombre}'
    
class Criticidad(models.Model):
    nombre = models.CharField(max_length=20)

    def __str__(self):
        return f'{self.nombre}'

class Product(models.Model):
    codigo = models.CharField(max_length=6, null=True, unique=True)
    nombre = models.CharField(max_length=150, null=True, unique=True)
    unidad = models.ForeignKey(Unidad, on_delete = models.CASCADE, null=True)
    familia = models.ForeignKey(Familia, on_delete = models.CASCADE, null=True)
    subfamilia = models.ForeignKey(Subfamilia, on_delete =models.CASCADE, null=True, blank=True)
    especialista = models.BooleanField(default=False)
    iva = models.BooleanField(default=True)
    activo = models.BooleanField(default=False)
    servicio = models.BooleanField(default=False)
    gasto = models.BooleanField(default=False)
    viatico = models.BooleanField(default=False)
    baja_item = models.BooleanField(default=False)
    image = models.ImageField(null=True, blank=True, upload_to='product_images')
    completado = models.BooleanField(default = False)
    #modificaciones para API
    critico = models.ForeignKey(Criticidad, on_delete = models.CASCADE, null=True)
    especs = models.TextField(blank=True, null=True)
    rev_calidad = models.BooleanField(default = False) 
    updated_by = models.ForeignKey(Profile, on_delete = models.CASCADE, null=True)
    
   
    #Estas opciones de guardado de creación y actualización las voy a utilizar en todos mis modelos
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(null=True)
    history = HistoricalRecords(history_change_reason_field=models.TextField(null=True))


    def __str__(self):
        return f'{self.codigo}-{self.nombre}'


    @property
    def imageURL(self):
        try:
            url = self.image.url
        except:
            url = ''
        return url
    
class Grado_Control(models.Model):
    nombre = models.CharField(max_length=10, null=True, unique=True)
    
    def __str__(self):
        return f'{self.nombre}'
    
#Este modelo fue enteramente creado para cumplimiento con la API
class Producto_Calidad(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(null=True)
    updated_by = models.ForeignKey(Profile, on_delete = models.CASCADE, null=True)
    producto = models.OneToOneField(Product, on_delete = models.CASCADE, null=True,  related_name='producto_calidad')
    requisitos = models.TextField(blank=True, null=True)
    #criterios_aceptacion = models.TextField(blank=True, null=True)
    documental = models.BooleanField(default= False)
    inspeccion = models.BooleanField(default= False)
    cumplimiento = models.BooleanField(default= False)
    g_documental = models.ForeignKey(Grado_Control, on_delete = models.CASCADE, null=True, blank= True, related_name='documental')
    g_inspeccion = models.ForeignKey(Grado_Control, on_delete = models.CASCADE, null=True, blank=True,related_name='inspeccion')
    g_cumplimiento = models.ForeignKey(Grado_Control, on_delete = models.CASCADE, null=True, blank=True, related_name='cumplimiento')

class Products_Batch(models.Model):
    file_name = models.FileField(upload_to='product_bash', validators = [FileExtensionValidator(allowed_extensions=('csv',))])
    uploaded = models.DateField(auto_now_add=True)
    activated = models.BooleanField(default=False)


    def __str__(self):
        return f'File id:{self.id}'

class Inventario_Batch(models.Model):
    file_name = models.FileField(upload_to='product_bash', validators = [FileExtensionValidator(allowed_extensions=('csv',))])
    uploaded = models.DateField(auto_now_add=True)
    activated = models.BooleanField(default=False)


    def __str__(self):
        return f'File id:{self.id}'



class Marca(models.Model):
    nombre = models.CharField(max_length=20, null=True, unique=True)
    familia = models.ForeignKey(Familia, on_delete = models.CASCADE, null=True, blank=True)

    def __str__(self):
        return f'{self.nombre}'





class Inventario(models.Model):
    producto = models.ForeignKey(Product, on_delete =models.CASCADE, null=True)
    distrito = models.ForeignKey(Distrito, on_delete = models.CASCADE, null=True)
    ubicacion = models.CharField(max_length=30, null=True, blank=True)
    estante = models.CharField(max_length=30, null=True, blank=True)
    marca = models.ManyToManyField(Marca, blank=True)
    almacen = models.ForeignKey(Almacen, on_delete = models.CASCADE, null=True)
    cantidad = models.DecimalField(max_digits = 14, decimal_places=2, default=0)
    cantidad_apartada = models.DecimalField(max_digits = 14, decimal_places=2, default=0)
    cantidad_entradas = models.DecimalField(max_digits = 14, decimal_places=2, default=0)
    price = models.DecimalField(max_digits=14, decimal_places=2, default=0)
    minimo = models.PositiveIntegerField(default =0)
    history = HistoricalRecords(history_change_reason_field=models.TextField(null=True))
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    complete = models.BooleanField(default=False)
    comentario = models.CharField(max_length=100, null=True, blank=True)
    activo_disponible = models.BooleanField(default=False)

    class Meta:
        unique_together = ('producto', 'almacen',)


    @property
    def get_total_producto(self):
        total_inv = (self.cantidad + self.apartada) * self.price
        return total_inv

    @property
    def costo_salidas(self):
        art_ordenados = self.articulosordenados_set.all()
        total = sum([item.get_costo_salidas for item in art_ordenados])
        return total
    
    @property
    def apartada(self):
        apartados = self.articulosordenados_set.all()

        # Para cada apartado, suma los valores disponibles_true y disponibles_false
        disponibles = sum([item.articulos_disponibles for item in apartados])
           
        return disponibles
    
    @property
    def apartada_entradas(self):
        articulos = self.articulosordenados_set.all()

        #Para cada apartado, suma los valores disponibles_true y disponibles_false
        disponibles = sum([item.articulos_totales for item in articulos])
           
        return disponibles

    def __str__(self):
        return f'{self.producto}'

class Tipo_Orden(models.Model):
    tipo = models.CharField(max_length=15, null=True)

    def __str__(self):
        return f'{self.id}:{self.tipo}'
    
class Plantilla(models.Model):
    nombre = models.CharField(max_length=100)
    descripcion = models.TextField(blank=True, null=True)
    comentario = models.TextField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    creador = models.ForeignKey(Profile, on_delete = models.CASCADE, null=True, related_name='Creador')
    modified_at = models.DateField(auto_now=True)
    modified_by = models.ForeignKey(Profile, on_delete = models.CASCADE, null=True)
    complete = models.BooleanField(default=False)
    # otros campos que consideres necesarios

class ArticuloPlantilla(models.Model):
    plantilla = models.ForeignKey(Plantilla, on_delete=models.CASCADE, null=True)
    producto = models.ForeignKey(Inventario, on_delete=models.CASCADE, null=True)
    cantidad = models.DecimalField(max_digits = 14, decimal_places=2, default=0)
    comentario_articulo = models.TextField(blank=True, null=True)
    comentario_plantilla = models.TextField(blank=True, null=True)
    modified_at = models.DateField(auto_now=True)
    modified_by = models.ForeignKey(Profile, on_delete = models.CASCADE, null=True)
    # otros campos que consideres necesarios

class Order(models.Model):
    folio = models.CharField(max_length=6, null=True, unique=True)
    last_folio_number = models.IntegerField(null=True)
    staff = models.ForeignKey(Profile, on_delete = models.CASCADE, null=True, related_name='Crea')
    proyecto = models.ForeignKey(Proyecto, on_delete = models.CASCADE, null=True)
    subproyecto = models.ForeignKey(Subproyecto, on_delete = models.CASCADE, null=True)
    distrito = models.ForeignKey(Distrito, on_delete = models.CASCADE, null=True)
    area = models.ForeignKey(Operacion, on_delete = models.CASCADE, null=True)
    #sector = models.ForeignKey(Sector, on_delete = models.CASCADE, null=True)
    superintendente = models.ForeignKey(Profile, on_delete = models.CASCADE, null=True, related_name='intendente')
    supervisor = models.ForeignKey(Profile, on_delete = models.CASCADE, null=True, related_name='supervisor')
    #activo = models.ForeignKey(Activo, on_delete = models.CASCADE, null=True)
    requisitar = models.BooleanField(null=True, default=False)
    requisitado = models.BooleanField(null=True, default=False)
    complete = models.BooleanField(null=True)
    tipo = models.ForeignKey(Tipo_Orden, on_delete=models.CASCADE, null=True)

user/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import get_user_model, authenticate
from .models import Profile


#Esta "form" fue creada heredando (inherit) las características de la "UserCreationForm" pero agregándole el "email"
class UserForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username','email','password1','password2']

class EmailLoginForm(AuthenticationForm):
    username = forms.EmailField(label='Email')

    def clean(self):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')

        if username is not None and password:
            self.user_cache = authenticate(self.request,
                                           username=username,
                                           password=password)
            if self.user_cache is None:
                raise forms.ValidationError(
                    self.error_messages['invalid_login'],
                    code='invalid_login',
                    params={'username': self.username_field.verbose_name},
                )
            else:
                self.confirm_login_allowed(self.user_cache)

        return self.cleaned_data

class Profile_Form(forms.ModelForm):

    class Meta:
        model = Profile
        fields = ['banco','cuenta_bancaria','clabe','image','phone','address']

templates/dashboard/add_product.html
{% extends 'partials/base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% load widget_tweaks %}
<html>
<head>
{% block title %}Agregar Producto/Servicio{% endblock %}
</head>
<body>
{% block content %}
<hr>
<h6>&nbsp;</h6>
<h6>&nbsp;</h6>
<h6>&nbsp;</h6>
<div class="container">
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <div class="card">
                <div class="card-header">
                  <h3>Agregar Producto/Servicio</h3>
                </div>
                <form method="POST" id='ProductForm' enctype='multipart/form-data'>
                    {% csrf_token %}
                    <div class="col-12">
                      <div class="input-group mb-3">
                      <span class="input-group-text" id="basic-addon1"><i class="fa-solid fa-list"></i></span>
                          <div class="form-floating form-floating-group flex-grow-1">   
                          {{form.codigo|add_class:"form-control"|append_attr:"placeholder=Código"}}
                          <label for="id_razon_social">Código*</label>
                          </div>
                      </div>
                    </div>
                    <div class="col-12">
                      <div class="input-group mb-3">
                      <span class="input-group-text" id="basic-addon1"><i class="fa-solid fa-list"></i></span>
                          <div class="form-floating form-floating-group flex-grow-1">   
                          {{form.nombre|add_class:"form-control"|append_attr:"placeholder=Nombre"}}
                          <label for="id_razon_social">Nombre*</label>
                          </div>
                      </div>
                    </div>
                    <div class="col-12">
                      <div class="input-group mb-3">
                      <span class="input-group-text" id="basic-addon1"><i class="fa-solid fa-list"></i></span>
                          <div class="form-floating form-floating-group flex-grow-1">   
                          {{form.unidad|add_class:"form-control"|append_attr:"placeholder=Unidad"}}
                          <label for="id_razon_social">Unidad*</label>
                          </div>
                      </div>
                    </div>
                    <div class="row">
                      <div class="col-12">
                          <div class="input-group mb-3">
                              <span class="input-group-text" id="basic-addon1"><i class="fa-solid fa-list"></i></span>
                              <div class="form-floating form-floating-group flex-grow-1">   
                                  {{form.familia}}
                              </div>
                          </div>
                      </div>
                  </div>
                  <div class="row">
                    <div class="col-12">
                        <div class="input-group mb-3">
                            <span class="input-group-text" id="basic-addon1"><i class="fa-solid fa-list"></i></span>
                            <div class="form-floating form-floating-group flex-grow-1">   
                                {{form.subfamilia}}
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-12">
                        <div class="input-group mb-3">
                            <span class="input-group-text" id="basic-addon1"><i class="fa-solid fa-list"></i></span>
                            <div class="form-floating form-floating-group flex-grow-1">   
                                {{form.critico}}
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-12">
                        <div class="input-group mb-3">
                            <span class="input-group-text" id="basic-addon1"><i class="fa-solid fa-list"></i>&nbsp;Especificaciones Técnicas</span>
                            <div class="form-floating form-floating-group flex-grow-1">   
                                {{form.especs|add_class:"form-control"|append_attr:"placeholder=Especificaciones Técnicas"}}
                            </div>
                        </div>
                    </div>
                </div>
                    <div class="form-check form-switch col-sm-3">
                      <label for="form.impuesto" class="form-check-label"><strong>IVA</strong></label>
                          {{form.iva|add_class:"form-check-input"}}
                    </div>
                    <div class="form-check form-switch col-sm-3">
                      <label for="form.impuesto" class="form-check-label"><strong>Servicio</strong></label>
                          {{form.servicio|add_class:"form-check-input"}}
                    </div>
                   
                    <div class="form-check form-switch col-sm-3">
                      <label for="form.impuesto" class="form-check-label"><strong>Gasto</strong></label>
                          {{form.gasto|add_class:"form-check-input"}}
                    </div>
                   
                    <div class="form-check form-switch col-sm-3">
                      <label for="form.impuesto" class="form-check-label"><strong>Activo</strong></label>
                          {{form.activo|add_class:"form-check-input"}}
                    </div>
                    <div class="form-check form-switch col-sm-3">
                      <label for="form.impuesto" class="form-check-label"><strong>Especialista</strong></label>
                          {{form.especialista|add_class:"form-check-input"}}
                    </div>
                    
                      {{form.image|add_class:"form-control"}}
                   
                    <h6>&nbsp;</h6>
                    <div class="container-fluid text-end">
                      <a class="btn btn-outline-secondary" href="{% url 'dashboard-product' %}">Cancelar</a>
                      <input class="btn btn-outline-info" type='submit' value="Actualizar">
                    </div>
                </form>
            </div>
        </div>

    </div>
</div>
</body>
</html>
<!--AJAX CALL-->
  <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
  <script>

var datosFamilia = {{familias_para_select2|safe}}

$(document).ready(function() {
    
    
    $('#id_familia').select2({
        allowClear: true,
        width: '100%',
        placeholder: 'Familia',
        data: datosFamilia,
        templateResult: formatRepo, // Función para renderizar los resultados
        templateSelection: formatRepoSelection // Función para renderizar la selección
    });
    $('#id_familia').on('select2:select', function(e){
        var data = e.params.data;
        familia_id = data.id
        if (familia_id != ""){
            mini_ajax(familia_id)  //Esta función la llamo cuando se selecciona un nuevo proyecto o cuando ya está seleccionado
        }
    }); //Aquí termina el select2:select
    var familiaSelect = $('#id_familia');
    var subfamiliaSelect = $('#id_subfamilia');
        $('#id_proyecto').on('select2:unselect', function(e){
           
            $('#id_subproyecto').val(null).trigger('change');
        });//Aquí termina el select2:unselect

    });

function mini_ajax(familia_id){
    //console.log(proyecto_id)
    $.ajax({
            url: "{% url 'ajax_load_subfamilias' %}",
            datatype: 'json',
            data: {
                'familia_id': familia_id
            },
            success: function (data) {
                actualizarSubfamilia(data); 
                //console.log(data)            
            }  
        })    

};

function actualizarSubfamilia(data) {
    //console.log(data)
    var $subfamiliaSelect = $('#id_subfamilia');
    $subfamiliaSelect.empty(); // Limpiar las opciones actuales

    // Añadir una opción placeholder
    $subfamiliaSelect.append(new Option('Seleccione una familia', '', true, true));

    // Añadir nuevas opciones
    $.each(data, function(index, subproyecto) {
        $subfamiliaSelect.append(new Option(subfamilia.nombre, subfamilia.id, false, false));
    });

    // Necesitas reinicializar el select2 para reflejar los cambios
    $subfamiliaSelect.trigger('change');
}
   
   $(document).ready(function() {
    $('#id_subfamilia').select2({
        allowClear: true,
        width: '100%',
        placeholder: 'Subfamilia',
        //data: ,
        templateResult: formatRepo, // Función para renderizar los resultados
        templateSelection: formatRepoSelection // Función para renderizar la selección
    });
});

$(document).ready(function() {
    $('#id_critico').select2({
        allowClear: true,
        width: '100%',
        placeholder: 'Criticidad',
        //data: ,
        templateResult: formatRepo, // Función para renderizar los resultados
        templateSelection: formatRepoSelection // Función para renderizar la selección
    });
});

function formatRepo (repo) {
    if (repo.loading) {
        return repo.text;
    }

    var $container = $("<div class='select2-result-repository clearfix'>" +
        "<div class='form-control form-control-lg select2-result-repository__title'></div>" +
        "</div>");

    $container.find(".select2-result-repository__title").text(repo.text);
    
    // Aquí podrías agregar más elementos al contenedor si es necesario.

    return $container;
}
function formatRepoSelection (repo) {
    return repo.text || repo.id;
}
  </script>
{% endblock %}

templates/dashboard/product_update_modal.html
{% extends 'partials/base_w_nav.html' %}
{% load static %}
{% load widget_tweaks %}
{% load crispy_forms_tags %}
<html>
<head>
{% block title %} Actualización de Producto {% endblock %}
</head>
<body>
{% block content %}
<div class="modal-dialog-lg" role="document">
    <form  hx-post="{{request.path}}" class="modal-content" id='ProductForm' enctype='multipart/form-data' data-subfamilias-url="{% url 'ajax_load_subfamilias' %}" novalidate>
    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title">Actualizar Productos</h5>
            <button class="btn-close cerrar" type="button" id="cerrar1" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body" style="color:white">
                {% csrf_token %}
                <label for="form.codigo" class="col-auto col-form-label"><strong>Código: {{item.codigo}}</strong></label>
                <br>
                <label for="form.nombre" class="col-auto col-form-label"><strong>Producto: {{item.nombre}}</strong></label>
                <br>
                <!--<label for="form.unidad" class="col-auto col-form-label my-1"><strong>Marca:</strong></label>
                    <div class="col-4">
                        {{ form.unidad|add_class:"form-control"}}
                    </div>
                <label for="form.familia" class="col-auto col-form-label my-1"><strong>Familia:</strong></label>
                    <div class="col-4">
                        {{ form.familia|add_class:"form-control"}}
                    </div>
                <label for="form.subfamilia" class="col-auto col-form-label my-1"><strong>Subfamilia:</strong></label>
                    <div class="col-4">
                        {{ form.subfamilia|add_class:"form-control"}}
                    </div>
                <label for="form.especialista" class="col-auto col-form-label my-1"><strong>Especialista:</strong></label>
                    <div class="col-4">
                        {{ form.especialista|add_class:"form-check-input"}}
                    </div>
                <label for="form.iva" class="col-auto col-form-label my-1"><strong>Iva:</strong></label>
                    <div class="col-4">
                        {{ form.iva|add_class:"form-check-input"}}
                    </div>
                <label for="form.activo" class="col-auto col-form-label my-1"><strong>Activo:</strong></label>
                    <div class="col-4">
                        {{ form.activo|add_class:"form-check-input"}}
                    </div>
                <label for="form.servicio" class="col-auto col-form-label my-1"><strong>Servicio:</strong></label>
                    <div class="col-4">
                        {{ form.servicio|add_class:"form-check-input"}}
                    </div>
                <label for="form.baja_item" class="col-auto col-form-label my-1"><strong>Baja Item:</strong></label>
                    <div class="col-4">
                        {{ form.baja_item|add_class:"form-check-input"}}
                    </div>
                <div class="col-10">
                        {{form.image|add_class:"form-control"}}
                </div>-->
                {{form|crispy}}
        </div>
        <div class="modal-footer">
                <button class="btn btn-success col-auto" id="crear" type="submit" >Actualizar</button>
                <a type="button" class="btn btn-secondary" id="cerrar" data-bs-dismiss="modal">Cerrar</a>
        </div>
    </div>
    </form>
</div>

<!--Este es el modal-->
<!--Este es el modal-->
<div class="modal fade" id ="dialog" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-lg" id="document" role="document" hx-target="this">

    </div>
</div>
<!--AJAX CALL-->
<script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
<script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<script>
$("#id_familia").change(function () {
      const url = $("#ProductForm").attr("data-subfamilias-url");  // get the url of the `load_subfamilias` view
      const familiaId = $(this).val();  // get the selected familia ID from the HTML input

      $.ajax({                       // initialize an AJAX request
        url: url,                    // set the url of the request (= localhost:8000/hr/ajax/load-cities/)
        data: {
          'familia_id': familiaId       // add the familia id to the GET parameters
        },
        success: function (data) {   // `data` is the return of the `load_subfamilias` view function
          $("#id_subfamilia").html(data);  // replace the contents of the subfamilia input with the data that came from the server
        }
      });
    });
</script>
{% endblock %}
</body>
</html>